### ISSUE TITLE
PangoWarning: couldn't load font

### ISSUE THREAD

**Issue by freesoft0000** [bleachbit/bleachbit#330] opened 2018-04-15 07:37 UTC
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\GUI.py:875: PangoWarning: couldn't load font "微软雅黑 Not-Rotated 9", falling back to "Sans Not-Rotated 9", expect ugly output.
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\GUI.py:875: PangoWarning: couldn't load font "微软雅黑 9", falling back to "Sans 9", expect ugly output.
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\CLI.py:219: PangoWarning: couldn't load font "微软雅黑 Bold Not-Rotated 14", falling back to "Sans Bold Not-Rotated 14", expect ugly output.
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\CLI.py:219: PangoWarning: couldn't load font "微软雅黑 Bold Not-Rotated 9", falling back to "Sans Bold Not-Rotated 9", expect ugly output.

**Comment by az0** [comment] 2018-04-15 15:05
That is an interesting bug report. I have a few questions

1. The log states "expect ugly output." Is the output ugly?

2. In BleachBit, please click **Help** - **System Information**. Then please look for a line that starts with `locale.getdefaultlocale`, and please paste that line here.

3. Did you find these messages in the `bleachbit.exe.log` file in the same folder as `bleachbit.exe`? When you closed BleachBit, did it give a popup error telling you to look in this log file?

**Comment by freesoft0000** [comment] 2018-05-06 07:10
system_cleaners_dir = G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\share\cleaners\
locale.getdefaultlocale = ('zh_CN', 'cp936')
os.getenv('APPDATA') = C:\Users\www\AppData\Roaming
os.getenv('LocalAppData') = C:\Users\www\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\www\AppData\LocalLow
os.getenv('Music') = C:\Users\www\Music
os.getenv('USERPROFILE') = C:\Users\www
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = f:\temp\temp
os.path.expanduser('~') = C:\Users\www\
platform.win32_ver[1]() = 6.1.7601
platform.platform = Windows-7-6.1.7601-SP1
platform.version = 6.1.7601
sys.argv = ['G:\\soft\\BleachBit\\BleachBit-2.0-portable\\BleachBit-Portable\\bleachbit.exe', '--gui', '--no-uac']
sys.executable = G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\bleachbit.exe
sys.version = 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\Diagnostic.pyo

**Comment by freesoft0000** [comment] 2018-05-06 07:12
The first floor is the content of bleachbit.exe.log

**Comment by freesoft0000** [comment] 2018-05-06 07:14
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\GUI.py:875: PangoWarning: couldn't load font "微软雅黑 Not-Rotated 9", falling back to "Sans Not-Rotated 9", expect ugly output.
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\GUI.py:875: PangoWarning: couldn't load font "微软雅黑 9", falling back to "Sans 9", expect ugly output.
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\CLI.py:219: PangoWarning: couldn't load font "微软雅黑 Bold Not-Rotated 14", falling back to "Sans Bold Not-Rotated 14", expect ugly output.
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\CLI.py:219: PangoWarning: couldn't load font "微软雅黑 Bold Not-Rotated 9", falling back to "Sans Bold Not-Rotated 9", expect ugly output.
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\GUI.py:875: PangoWarning: couldn't load font "微软雅黑 Not-Rotated 9", falling back to "Sans Not-Rotated 9", expect ugly output.
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\GUI.py:875: PangoWarning: couldn't load font "微软雅黑 9", falling back to "Sans 9", expect ugly output.
G:\soft\BleachBit\BleachBit-2.0-portable\BleachBit-Portable\library.zip\bleachbit\GUI.py:470: GtkWarning: inner_clipboard_window_procedure: assertion `success' failed

**Comment by dinojr** [comment] 2019-01-20 20:05
I only ad this problem when running bleachbit with sudo. Seems to be caused by some permission error since
` chmod -Rf 777 /usr/share/fonts/*`
fixed it

**Comment by az0** [comment] 2019-03-04 00:24
I am closing because of no reply

@freesoft0000  When you can reply to my comment from January 29, please reopen this ticket.

**Closed by az0** 2019-03-04 00:24 UTC
Labels: bug
