### ISSUE TITLE
Error version # 1.12

### ISSUE THREAD

**Issue by whateveroldtimer** [bleachbit/bleachbit#236] opened 2017-09-22 05:33 UTC
Error in execution of <bleachbit.Command.Function instance at 0x02C53A08>

Windows 7 64bit
Bleachbit Version # 1.12
Uninstalled programs from system still listed in bleachbit, in my case, Skype and Opera web browser.

**Comment by az0** [comment] 2017-09-23 03:06
Uninstalling Skype and Opera remove the application but not the configuration files. Some people still want to clean the configuration files for uninstalled software to maintain privacy or free disk space, so it is normal to see uninstalled applications.

Regarding the "Error in execution": Would you please test this with BleachBit version 1.17 or later? There have been many fixes for version 1.17, and the feedback for this release has been positive. 

If this version works, please let me know here, so I can close the ticket. If this version still gives you an error, please try to narrow it down to a single option (a single check box). There is a good chance it has to do with an option under Google Chrome.

**Comment by whateveroldtimer** [comment] 2017-09-23 13:18
cleaned out skype and opera, no longer listed in 1.12, updated to 1.17 for
testing like asked
now skye and opera are back in the list , go figure.


Bleachbit 1.17

Error in execution of <bleachbit.Command.Function instance at 0x0379CE90>

help / about bleacbit, clicked on link in window https://www.bleachbit.org
error window opens

Could not show link
no application is registered as handling this file

while bleachbit is open and firefox is also, , it tells me firefox is stull
running and to close firefox.
close firefox and it thinks firefox is still running, need to restart
bleachbit.
will check the rest of 1.17, hope this helps. Tom.

**Comment by whateveroldtimer** [comment] 2017-09-23 13:34
update to 1.17, did a search for skype and opera on C: drive and found
skype.xml and opera.xml in, C:\Program FIles(x86)\BleachBit\share\cleaners
i removed the .xml files from the folder and sky and opera are no longer in
the list
will run clean for errors after doing this but have to close firefox and
this email window to test.
Tom.

**Comment by whateveroldtimer** [comment] 2017-09-23 13:53
ok, update #2 bleachbit 1.17 after removing skype.xml and opera.xml
error
Error in execution of <bleachbit.Command.Function instance at 0x0340EA30>

 i am wondering where bleachbit is getting info on the system telling
bleachbit that the programs are installed to make an
 .xml files for them ? perhaps i missed something, as i it did clean by
hand in explorer seach and the registry.
oh well, let me know and i will look.

Sorry for all the emails....can't test wile email is open in firefox,

hope this helps, need more info of testing on my end, email me, Tom...

**Comment by whateveroldtimer** [comment] 2017-09-23 14:20
Update # 3, bleachbit 1.17,  closed firefox ran bleachbit, keep getting an
error, so ran bleachbit 11 times
just bleachbit while doing nothing else on the system and the error numbers
keep changing, strange,
here is the list of numbers

1 - 0x039CF238
2 - 0X03968EB8
3 - 0X03912EB8
4 - 0X039D2EB8
5 - 0X0394DEB8
6 - 0X039A2EB8
7 - 0X039CDEB8
8 - 0X03902EB8
9 - 0X039A2EB8
10 - 0X03932EB8
11 - 0X03A62EB8

# 6 and 9 are the same

ok, thats all i have for now waiting on info from you on more testing,
Tom....

**Comment by whateveroldtimer** [comment] 2017-09-23 14:41
Update # 4 ????, ok close firefox, ran bleachbit, bleachbit cleaned
internet explorer files, 115.1kB cleaned
files deleted: 8
Errors: 1
Firefox cannot be cleaned because it is currently running. Close it, and
try again.
firefox is closed, but, didn't get the execution number error.
maybe it's doing something with firefox ?
hope this helps locate the error a bit

OHHH..DUHH  Firefox 55.0.3 (64bit), my bad, should have told you that.
Tom..

**Comment by ROCKNROLLKID** [comment] 2017-09-23 17:30
For #4, make sure Firefox isn't running in the background. Check in task manager.

2 of your issues sound like maybe BleachBit installation got corrupted. Do you have any anti-virus/anti-malware installed as if so is it blocking BleachBit? I would suggest maybe uninstalling BleachBit and reinstalling it again. You may want to try the latest nightly build of BleachBit, as 1.17 beta was released a month ago and there has been several fixes since then (though nothing specific to your issues). You can find them here: http://ci.bleachbit.org/

**Comment by whateveroldtimer** [comment] 2017-09-24 02:12
Do you have any anti-virus/anti-malware installed, no, am running the
latest build as stated in the emails.

**Comment by whateveroldtimer** [comment] 2017-09-25 21:14
Uninstalling Skype and Opera remove the application but not the
configuration files. Some people still want to clean the configuration
files for uninstalled software to maintain privacy or free disk space, so
it is normal to see uninstalled applications.

i thought this was the reason for using bleachbit?????, you're .xml files
are the problem, i am done with this,

 i am no longer interested in you're program and the nonsence and excuses
you are using to not fix you're program problems out..good day sir...

**Comment by ROCKNROLLKID** [comment] 2017-09-25 21:46
whateveroldtimer: I am sorry you are not having a good experience with BleachBit. Please note that XML files are just cleaning rules and have not nothing to do with your issue. The error in execution has something to do with BleachBit internally. I have been testing both Opera and Skype and I have not been able to reproduce this issue. Because it isn't something that can be replicated easily, it is much harder to fix then. The suggestions we are giving you are to help fix this issue for us. We need to make sure 1. it isn't a user issue 2. the issue hasn't already been resolved in a recent commit. 3. It isn't something else, like anti-malware, that mgiht be causing this or possibly a corrupted installation.

**Comment by whateveroldtimer** [comment] 2017-09-27 00:15
It's not a user issue in the first place if you read my emails, but you
ignored the facts of what i told you about .xml files in bleachbit that
caused the problem being listed, got on with you're self Young man, listen
to the old man who know whats he is talking about, but you indeed like to
insult a person, lol, childish  acts

**Comment by az0** [comment] 2017-12-15 22:02
Multiple errors with the symptom `bleachbit.Command.Function instance at 0x02C53A08` were recently fixed for Firefox and Google Chrome, and then can be tested with [BleachBit 1.17.573](http://ci.bleachbit.org/?prefix=1.17.573/)

**Comment by whateveroldtimer** [comment] 2017-12-16 18:24
Cool, thanks for the update

**Comment by az0** [comment] 2017-12-30 23:07
Please test [BleachBit version 1.19 beta](https://www.bleachbit.org/news/bleachbit-119-beta) and reply in this bug ticket with how it goes. I think this version will fix this error. Also, please reopen this ticket if the error messages continues.

**Closed by az0** 2017-12-30 23:07 UTC
Labels: bug
