### ISSUE TITLE
Exception occurred after cleaning related plyer and pop-up notification

### ISSUE THREAD

**Issue by muessli** [bleachbit/bleachbit#822] opened 2020-03-25 22:08 UTC
I use Win 10 Home, version 1909 and Bleachbit 3.9.0.
### When I try to clean Firefox, the following messages appear:
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\plyer\utils.py", line 96, in _ensure_obj
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 310, in run
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 767, in worker_done
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 107, in notify
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 94, in notify_plyer
  File "C:\Python34\lib\site-packages\plyer\utils.py", line 114, in __getattribute__
  File "C:\Python34\lib\site-packages\plyer\utils.py", line 100, in _ensure_obj
  File "C:\Python34\lib\traceback.py", line 252, in print_exc
  File "C:\Python34\lib\traceback.py", line 170, in print_exception
  File "C:\projects\bleachbit\bleachbit\Log.py", line 115, in write

**Comment by muessli** [comment] 2020-03-25 22:12
Sorry, it is independent of Firefox!

**Comment by muessli** [comment] 2020-03-25 22:14
Issue reOpened.

**Comment by az0** [comment] 2020-03-26 03:45
I reproduced this on Windows 10 (Spanish) on Windows 3.9.0 beta (build 1570) when deleting files in %temp%.

The problem is triggers during an attempt to launch a popup notification.  This happens when either cleaning takes a while or if the BleachBit window is not in the foreground when it's done.

I will look into it

```
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\plyer\utils.py", line 96, in _ensure_obj
ImportError: No module named 'plyer.platforms'
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 310, in run
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 767, in worker_done
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 107, in notify
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 98, in notify_plyer
  File "C:\Python34\lib\site-packages\plyer\facades\notification.py", line 84, in notify
  File "C:\Python34\lib\site-packages\plyer\facades\notification.py", line 90, in _notify
NotImplementedError: No usable implementation found!
```

**Comment by az0** [comment] 2020-03-26 03:59
I put in a potential fix. Perhaps you could test it? In about 15 minutes, it will be available on the CI build site as [3.9.0.1573](https://ci.bleachbit.org/). Other builds, even newer builds such as 1574, might not have the fix, so for now, please test 1573.

**Comment by muessli** [comment] 2020-03-26 16:42
with Build 1573:
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\plyer\utils.py", line 96, in _ensure_obj

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 310, in run
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 767, in worker_done
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 107, in notify
  File "C:\projects\bleachbit\bleachbit\GUI.py", line 94, in notify_plyer
  File "C:\Python34\lib\site-packages\plyer\utils.py", line 114, in __getattribute__
  File "C:\Python34\lib\site-packages\plyer\utils.py", line 100, in _ensure_obj
  File "C:\Python34\lib\traceback.py", line 252, in print_exc
  File "C:\Python34\lib\traceback.py", line 170, in print_exception
  File "C:\projects\bleachbit\bleachbit\Log.py", line 115, in write

Can you dsplay the Build-No. in the "About Bleach"-Dialog?
Sorry, I'm a new github user
Dont know how to replay/save an message

> 
> 
> I put in a potential fix. Perhaps you could test it? In about 15 minutes, it will be available on the CI build site as [3.9.0.1573](https://ci.bleachbit.org/). Other builds, even newer builds such as 1574, might not have the fix, so for now, please test 1573.

**Comment by muessli** [comment] 2020-03-26 16:44
Is "Close and commnet" and then Reopen" the right course of action?

**Comment by az0** [comment] 2020-03-27 02:36
Thank you for testing build 1573. I will try another fix.

> Is "Close and commnet" and then Reopen" the right course of action?

No, use "close and comment" only when your issue is resolved. It's not yet resolved, so for now click the "comment" button to add a comment.

**Comment by az0** [comment] 2020-03-28 21:43
Here is how I reproduced earlier

1. I downloaded a build from AppVeyor (also ci.bleachbit.org)
1. I installed on a Windows that had no Python installation
1. I checked many boxes, so the preview or delete would take longer
1. I added 1000 empty files to %temp% to make it take longer
1. I ran a preview
1. While the preview was running, I put BleachBit in the foreground, so the window did not have focus

If preview is too fast, switch to delete, and enable the "overwrite" option in the preferences. This will slow it down.

The notification triggers if elapsed time >10 or the window is in the background.

I think the root cause is py2exe is not including the pyler module.

**Comment by mkhon** [comment] 2020-03-31 18:11
Fixed in #834

**Comment by mkhon** [comment] 2020-03-31 18:13
By the way, it seems that gi Notify should not be installed (this should reduce py2exe build size):

```
- 'pygi-aio.exe %PYTHON_HOME% GTK Notify'
```

**Comment by az0** [comment] 2020-03-31 23:12
@muessli 

Would you please test Max's fix? In a few minutes, there will be a 3.9.1.x build available on the [CI site](https://ci.bleachbit.org/). Please test and let us know whether it helped.

**Comment by az0** [comment] 2020-03-31 23:13
P.S., if it works well, then there should be a popup notification with the notice "done"

**Comment by az0** [comment] 2020-04-04 19:17
I tested with build 1613 on Windows 10 (non-developer system). On my last test, it clearly worked when the elapsed cleaning time was 71 seconds (5001 files), debug logging was enabled, and I was running bleachbit_console.exe. Earlier I didn't see the popup in another test, but I probably just missed it.

**Closed by az0** 2020-04-04 19:17 UTC
Labels: bug
