### ISSUE TITLE
Bleachbit identifies multiple files for deletion but fails to delete them "Access is denied"

### ISSUE THREAD

**Issue by Lochabar** [bleachbit/bleachbit#1014] opened 2020-09-11 01:54 UTC
Bleachbit 4.0 is identifying multiple files in c:\projects\bleachbit\* for deletion, but fails to delete them.
![Bleachbit](https://user-images.githubusercontent.com/17562417/92841222-aa45a380-f3a7-11ea-8139-8eb947d52ae0.png)

I tried to add c:\projects/bleachbit from the search but could not locate the directory in the options.

Similar problem with a windows cache location
![Bleachbit2](https://user-images.githubusercontent.com/17562417/92841287-bcbfdd00-f3a7-11ea-8c16-2e5746bc7df2.png)

**Comment by az0** [comment] 2020-09-22 03:16
This looks like an issue fixed in [BleachBit 4.1.0 beta](https://www.bleachbit.org/news/bleachbit-410-beta). Please update, test again, and write a comment here to let me know how it went.

By the way, the `c:\projects` path is confusing. It does not refer to your system. It refers to the location of the source code on the build server. It's useful for diagnosing issues, but otherwise you can ignore it.  The files affected on your system are under `c:\windows\logs` and `C:\programdata\`

**Comment by Lochabar** [comment] 2020-09-22 12:41
I ran the beta and it no longer produced the 450+ errors it did previously. However it looks like there is another error.

![Bleachbit beta](https://user-images.githubusercontent.com/17562417/93883247-ef6ead00-fca6-11ea-951e-842852204a34.png)

**Comment by az0** [comment] 2020-09-26 19:40
The first error was `access is denied`, and thank you for confirming that's fixed. I added this error message to the title of this GitHub issue.

The second error `no such table: moz_origins` is different. It looks like a duplicate of https://github.com/bleachbit/bleachbit/issues/1002 . It's easier to manage issues when there is one problem per issue, so I'd like to close this ticket. You can either tag along on issue 1002 or file your own about moz_origins.

**Closed by az0** 2020-09-26 19:40 UTC
