### ISSUE TITLE
When wiping free disk space, only one 4GB file is written to the 8GB thumb drive and then deleted

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#1051] opened 2020-11-11 18:52 UTC
```
clean_operation('_gui'), options = '[]'
Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space.Wiping path: G:\
Creating new, temporary file for wiping free space.
Wrote 1 files and 4,294,967,296 bytes in 1,003 seconds at 4.28 MB/s
Overwrite free disk space G:\ 0 

Disk space recovered: 0
Files deleted: 0
Special operations: 1
elapsed time: 1014 seconds
```
Windows 8 SL (64-bit)
BleachBit version 4.1.1-portable
Build number 1766
![Drive properties](https://user-images.githubusercontent.com/44164186/98851848-e361c900-2467-11eb-8389-4920bdfac3f2.png)

**Comment by az0** [comment] 2020-11-12 15:36
Good information, ediowar.

This seems like a regression related to the FAT32 file limit.

**Comment by Marvin0401** [comment] 2020-11-30 01:22
Yes, it seems like a regression related to the FAT32 file limit. Let me fix it soon.

**Comment by Marvin0401** [comment] 2020-12-08 16:25
Hi ediowar, I've fixed this issue. Could you test with this fork "https://github.com/Marvin0401/bleachbit.git"? If you need to get help from me about this issue, please feel free to let me know. Thanks

**Comment by ediowar** [comment] 2020-12-08 22:55
@Marvin0401 For testing on Windows, I need a portable version.

**Comment by ediowar** [comment] 2020-12-08 22:56
@Marvin0401 for testing on Windows, I need a portable version.

**Comment by ediowar** [comment] 2020-12-08 22:57
@Marvin0401, for testing on Windows, I need a portable version.

**Comment by az0** [comment] 2020-12-09 06:33
@MarvinQC
Submit a PR, and AppVeyor will automatically build and publish binaries for
users to test.

**Comment by Marvin0401** [comment] 2020-12-15 13:36
@ediowar , Sorry for late response. Please check it with this PR.
[BleachBit-4.1.1-portable-20201215-Marvin.zip](https://github.com/bleachbit/bleachbit/files/5696220/BleachBit-4.1.1-portable-20201215-Marvin.zip)

**Comment by Marvin0401** [comment] 2020-12-15 13:37
@az0 , AppVeyor is working well for building, but I've got failed to deploy S3 due to access_key_id.

**Comment by az0** [comment] 2020-12-16 23:26
@Marvin0401 

> @az0 , AppVeyor is working well for building, 

I suppose it's building in your own AppVeyor account. Normally when a developer submits a PR to this repository (bleachbit/bleachbit), it builds in the [same AppVeyor account](https://ci.appveyor.com/project/az0/bleachbit/history). In other words, there is not a need for each developer to have his own AppVeyor account.

> but I've got failed to deploy S3 due to access_key_id.

I think you are trying to push to my bucket using `bleachbitci` your AWS keys, but you don't have access to modify my bucket.

If you were to submit a PR to this repository, AppVeyor would build it but not publish it to S3 because of the configuration/policy, but the build hosted on AppVeyor is sufficient for users to test.

**Comment by ediowar** [comment] 2020-12-22 19:29
@Marvin0401 Thank you. Checked it out. There is no issue.

**Comment by az0** [comment] 2020-12-22 20:43
I'll reopen the issue until the code is merged into this repository.

@Marvin0401 
Please file a PR with the commit(s) just for this issue. Thanks in advance

**Comment by az0** [comment] 2020-12-22 20:43
@ediowar 
Thanks for testing :)

**Comment by Marvin0401** [comment] 2020-12-23 00:51
@ediowar, Thank you for testing. :)

**Comment by Marvin0401** [comment] 2020-12-23 00:52
@az0 , May I send pull request?

**Comment by ediowar** [comment] 2020-12-23 00:53
https://github.com/bleachbit/bleachbit/issues/1051#issuecomment-749766403

**Closed** 2021-02-20 22:36 UTC
Labels: bug, priority:high
