### ISSUE TITLE
UnicodeDecodeError while running thumbnail clean

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#800] opened 2020-03-01 23:00 UTC
```
BleachBit version 3.9.0
Build number 1545
platform.win32_ver[1]() = 6.2.9200
platform.platform = Windows-8-6.2.9200-SP0
platform.version = 6.2.9200
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
```
The box for Windows Explorer - Thumbnails is checked. 
```
Error: windows_explorer.thumbnails: Function: Run external command: taskkill.exe /f /IM explorer.exe
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Action.py", line 546, in run_process
  File "C:\projects\bleachbit\bleachbit\General.py", line 158, in run_external
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 142, in execute
  File "C:\projects\bleachbit\bleachbit\Action.py", line 553, in run_process
RuntimeError: Exception in external command
Command: taskkill.exe /f /IM explorer.exe
Error: 'utf-8' codec can't decode byte 0x93 in position 0: invalid start byte
Run external command: C:\windows\explorer.exe C:\windows\explorer.exe 0 

Disk space recovered: 0
Files deleted: 0
Special operations: 1
Errors: 1
```

**Comment by az0** [comment] 2020-03-02 01:03
This is an encoding issue. @ediowar , which language is your Windows set to?

I tried to reproduce on Windows 10 Spanish with BleachBit build 1544. I tried in both administrator mode and non-administrator mode, and I could not reproduce it.

**Comment by ediowar** [comment] 2020-03-02 08:53
Windows 8 SL Russian.

**Comment by az0** [comment] 2020-03-21 17:14
Would you please try BleachBit 3.9.0.1568 from the [CI build site](https://ci.bleachbit.org/)? It will be available in a few minutes

I am not sure this is the right fix, so it's a separate branch. This means by default the change won't be in future builds, such as 1569.

**Comment by ediowar** [comment] 2020-03-25 20:54
I tried BleachBit 3.9.0.1568. The fix is right. However, 1571 does not have this error.

**Comment by az0** [comment] 2020-03-26 03:29
After reconsideration, I merged the fix into the master branch, so 1568 and 1571 and future builds all have the same fix. I am glad to hear it works, and I am closing this issue.

**Closed by az0** 2020-03-26 03:29 UTC
Labels: bug, bug:encoding, priority:high
