### ISSUE TITLE
RunDLL when portable folder contains space

### ISSUE THREAD

**Issue by indig0F10w** [bleachbit/bleachbit#1053] opened 2020-11-14 12:15 UTC
The infamous error:
_RunDLL
There was a problem starting "Whatever path to BleachBit portable".
The specified module could not be found._

This error is NOT related to any specific Windows version and it is present since BleachBit v3 as I can see.

This error is directly related to BleachBit code which requires some DLL to be in exact path/folder as extracted folder name: "BleachBit-Portable". If you remove minus symbol from path and replace it with space (BleachBit Portable) BleachBit gives DLL error. It doesn't matter on which drive you extracted BleachBit nor does antivirus or firewall block anything.

Thanks for BleachBit.

P.S. Please make an option for users to be able to change language without having to manually delete language files.

**Comment by az0** [comment] 2020-11-14 18:08
> If you remove minus symbol from path and replace it with space (BleachBit Portable) BleachBit gives DLL error. It doesn't matter on which drive you extracted BleachBit nor does antivirus or firewall block anything.

I will put this in the title to make it more clear.
 
> Thanks for BleachBit.

You're welcome.

> P.S. Please make an option for users to be able to change language without having to manually delete language files.

One issue per ticket, please.

**Comment by Marvin0401** [comment] 2020-12-08 16:44
Hi Andrew, Let me fix this issue. Ok?

**Comment by Marvin0401** [comment] 2021-03-22 03:24
Hi @az0 , I've reversed our exe using IDA to fix this issue, but I did not get reasonable results yet. It occured when we run it on other drives, not C drives and path includes this pattern, "xx xx xx". That's why I think it would be related to PyGtk issues and if we upgrade python version, it will be fixed automatically.

**Comment by az0** [comment] 2021-03-27 20:23
> Hi @az0 , I've reversed our exe using IDA to fix this issue, but I did not get reasonable results yet. It occured when we run it on other drives, not C drives and path includes this pattern, "xx xx xx". That's why I think it would be related to PyGtk issues and if we upgrade python version, it will be fixed automatically.

@Marvin0401 

Yes, this is one of many reasons that https://github.com/bleachbit/bleachbit/issues/848 is important to fix ASAP.

**Comment by az0** [comment] 2021-05-18 05:14
I cannot reproduce on Windows 10 with BleachBit build 1900 (revision ac97e1e4dce9cdf88043997d98d46d9ba7e3209d) when executable is on a fat32 drive at `e:\xx xx xx\bleachbit.exe`

**Comment by az0** [comment] 2023-01-04 15:42
We now have a build with major updates to the underlying frameworks. 

@indig0F10w , would you please test [build 2310](https://ci.bleachbit.org/?prefix=dl/4.4.2.2310-mkhon-python310/)?

**Comment by indig0F10w** [comment] 2023-01-06 12:28
Hello, this has been tested and confirmed to work flawlessly.

Thanks.

**Comment by mkhon** [comment] 2023-01-08 00:46
@az0 this can now be closed?

**Comment by rados** [comment] 2023-01-08 21:09
This one seems related with #1384.

**Comment by az0** [comment] 2023-01-09 13:51
@mkhon Yes, closed as resolved

**Closed** 2023-01-09 13:51 UTC
Labels: bug

**Comment by az0** [comment] 2024-12-30 16:41
@Alfamari 
The fix here helped other people, so let's leave this issue ticket as closed, but please create a fresh, new issue to track your problem. Please include your Windows version number and any other details that might help to reproduce the issue. Is BleachBit running as installed or portable?

**Comment by az0** [comment] 2025-03-20 03:31
[BleachBit 4.9.1 alpha](https://www.bleachbit.org/news/bleachbit-491-alpha) was released with this fix. This is digitally signed, unlike the CI builds.
