### ISSUE TITLE
Why are MBs of files shown as deleted every time BleachBit is run

### ISSUE THREAD

**Issue by githubgomer** [bleachbit/bleachbit#1748] opened 2024-12-22 02:59 UTC
When I run Bleachbit, I'll also usually run CCleaner and Advanced Uninstaller v11 (later versions stink). Why does BleachBit claim to have removed megabytes (megabits?) of data no matter how many times it's run in one session? That is, I'll run it, it says 282MB remove. I'll run it again immediately, and it says it removed the same or a lesser amount.

**Comment by az0** [comment] 2024-12-22 17:30
The second time you run "clean," please check the cleaning log shown on the main window. Specifically, look for the verbs such as _delete_, _marked for deletion_, and _vacuum_. Which verbs are you seeing? Feel free to copy and paste a few lines of the log here in your reply.

**Comment by az0** [comment] 2024-12-31 17:53
No reply, so closing. If you have follow-up, add a comment here and re-open this issue ticket.  Until then, my guess is the cause is files are "marked for deletion" which means deleted when Windows reboots.

**Closed by az0** 2024-12-31 17:53 UTC
Labels: question
