### ISSUE TITLE
TypeError: 'int' object is not subscriptable in Windows Wipe

### ISSUE THREAD

**Issue by Surfride10** [bleachbit/bleachbit#1035] opened 2020-10-26 12:27 UTC
I am receiving the errors below with 4.1.0 attempting to delete app crash reports in WER in .\programdata...  target is 2012r2

Thanks!

~David

Delete 105.4kB C:\ProgramData\Microsoft\Windows\WER\ReportQueue\NonCritical_7.9.9600.19810_535d16b2204d8b274f9fc255741fd7bce31c71_00000000_cab_0e352a93\ReportingEvents.log
Error: system.logs: Command to delete C:\ProgramData\Microsoft\Windows\WER\ReportQueue\NonCritical_7.9.9600.19810_535d16b2204d8b274f9fc255741fd7bce31c71_00000000_cab_0e352a93\WindowsUpdate.log
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 82, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 350, in delete
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 789, in wipe_contents
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 968, in file_wipe
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 281, in choose_if_bridged
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 280, in <listcomp>
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 226, in extents_a_minus_b
TypeError: 'int' object is not subscriptable
Delete 3.1kB C:\ProgramData\Microsoft\Windows\WER\ReportQueue\NonCritical_7.9.9600.19810_dd1e2b8f33e5e14571ee70ee48ef48f93e43ea59_00000000_cab_0bf86315\Report.wer
Error: system.logs: Command to delete C:\ProgramData\Microsoft\Windows\WER\ReportQueue\NonCritical_7.9.9600.19810_dd1e2b8f33e5e14571ee70ee48ef48f93e43ea59_00000000_cab_0bf86315\ReportingEvents.log
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 82, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 350, in delete
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 789, in wipe_contents
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 968, in file_wipe
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 281, in choose_if_bridged
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 280, in <listcomp>
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 226, in extents_a_minus_b
TypeError: 'int' object is not subscriptable
Error: system.logs: Command to delete C:\ProgramData\Microsoft\Windows\WER\ReportQueue\NonCritical_7.9.9600.19810_dd1e2b8f33e5e14571ee70ee48ef48f93e43ea59_00000000_cab_0bf86315\WindowsUpdate.log
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 82, in execute
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 350, in delete
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 789, in wipe_contents
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 968, in file_wipe
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 281, in choose_if_bridged
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 280, in <listcomp>
  File "C:\projects\bleachbit\bleachbit\WindowsWipe.py", line 226, in extents_a_minus_b
TypeError: 'int' object is not subscriptable

**Comment by Marvin0401** [comment] 2020-11-30 01:24
Target OS is windows server 2012 r2?

**Comment by Marvin0401** [comment] 2020-12-08 16:26
Hi David,

**Comment by Marvin0401** [comment] 2020-12-08 16:28
I've fixed this issue. Could you test with this fork "https://github.com/Marvin0401/bleachbit.git"? Please let me know if you still have this issue. I would love to fix it. Thanks

**Comment by az0** [comment] 2020-12-10 00:58
@Marvin0401 
Please submit a bug-specific PR, so AppVeyor builds a binary. This makes it easier for users to test.

**Comment by Marvin0401** [comment] 2020-12-15 14:01
Please check with this PR. I will wait for your feedback.
[BleachBit-4.1.1-portable-20201215-Marvin.zip](https://github.com/bleachbit/bleachbit/files/5696253/BleachBit-4.1.1-portable-20201215-Marvin.zip)

**Comment by az0** [comment] 2021-02-14 01:19
Before testing Marvin's fix, I tried to reproduce the error on Windows 10 with BleachBit 4.2.0 (build 1829), but I couldn't reproduce it. Later I will try again.

**Comment by az0** [comment] 2021-02-20 22:38
@Surfride10 
Thank you for the bug report. I accepted and merged Marvin's fix. In a few minutes, it will post to the [official BleachBit CI site](https://ci.bleachbit.org/) as build 4.2.0.1830. Would you please test it and then write a comment here to confirm it was fixed?

**Comment by az0** [comment] 2021-03-12 04:08
@Surfride10 
I haven't heard back, so I will assume this is fixed. If you have any information, please add a comment to this ticket.

**Closed by az0** 2021-03-12 04:08 UTC
Labels: bug, priority:high

**Comment by az0** [comment] 2021-06-04 19:34
@Surfride10 
The fix was released in [version 4.3.0 beta](https://www.bleachbit.org/news/bleachbit-430-beta). Give it a try, and let me know in this issue whether it was fixed.
