### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by vlone** [bleachbit/bleachbit#320] opened 2018-03-17 20:15 UTC
Hi,

Just upgraded to BleachBit 2.0 I a, experimenting a bug that I never had.

Runtime error !
P:\Program Files (x86)\BleachBit\bleachbit.exe
This application has requested the runtime to terminate it in an unusual way

Running Windows 10 Entreprise LTSB with latest updates.
I5 4690K, 12go DDR3, GTX 690
Trying to use BleachBit with all cases checked except free space cleaning

Thanks

**Comment by az0** [comment] 2018-03-18 21:13
This is an unusual error message. Thanks for reporting it.

Which antivirus do you use? If you temporarily disable it or put it into game mode (just for troubleshooting), does the error still happen?

Can you narrow down which option causes this? My guess is to start with the options in the System category. For example, Recycle Bin.

Does it happen with preview or just with clean?

**Comment by vlone** [comment] 2018-03-19 00:02
Hi,

No antivirus installed (windows defender disabled)
This happen when cleaning (i do not use the preview option)
Will try to uncheck recycle bin tomorrow

Thanks
________________________________

**Comment by vlone** [comment] 2018-04-02 07:56
Hi
Unfortunately not, due to an other problem the PC has been completely clean installed, and now no problems at all
Thanks
________________________________

**Comment by az0** [comment] 2018-04-02 13:18
OK, thank you for letting me know. I will close this ticket.

If the same error happens again later, please re-open this ticket

**Comment by motowizlee** [comment] 2018-04-12 01:28
OS: Windows 10 Pro 10.0.16299
App version: BleachBit 2.0 Portable

Would like to report the same error. Screenshot as below. The error seems to go away after unchecked Adobe Reader (The one with Cache, Most Recently Used, and Temporary Files as the subcategories)

![image](https://user-images.githubusercontent.com/27324034/38651321-2cc0ba2a-3e33-11e8-9674-72a1fecdff9f.png)

**Comment by az0** [comment] 2018-04-12 04:48
@motowizlee 
Thanks for the report. The standard BleachBit 2.0 version does not have much extra debugging, but you can try the [troubleshooting procedure](https://docs.bleachbit.org/doc/troubleshooting.html). In a future version I will add better debugging.

For now, my suggestion is to disable all options, and then execute them individually. Would you please try that with each checkbox under Adobe?

**Comment by az0** [comment] 2018-05-05 00:51
@motowizlee 
Have you had a chance to try this step? If so, let me know which checkbox causes the crash.
>For now, my suggestion is to disable all options, and then execute them individually. Would you please try that with each checkbox under Adobe?

**Comment by motowizlee** [comment] 2018-05-05 06:15
@az0 Sorry, recently very tight-up with work. Will certainly try the steps when I have bandwidth. Thanks for the follow up!

**Comment by Sunii** [comment] 2018-06-01 18:33
Also having this issue, seems to only happen when Adobe, Google Chrome, or Firefox are checked. I've tried checking each value under "Adobe" separately but all 3 options cause the Runtime Error.

Running Bleachbit Debugging Terminal gives "Fatal Python error: Interpreter not initialized (version mismatch?)" When trying to clean one of the mentioned apps.

Bleachbit 2.0 installed with Chocolatey using winapp2.ini
Windows 10 Enterprise Version 10.0.16299 Build 16299

**Comment by az0** [comment] 2018-06-03 23:11
@Sunii  That was helpful information. Do you get the same error if you uninstall BleachBit using Chocolatey and then install BleachBit "normally" by downloading the installer from www.bleachbit.org ?

@vlone  @motowizlee  Did you use Chocolatey to install BleachBit?

@Sunii @vlone @motowizlee  Do you know of any other installations of Python on your computer? Maybe you installed Python yourself, or maybe you installed (another application) besides BleachBit that uses Python?

**Comment by Sunii** [comment] 2018-06-04 01:52
@az0 I do have python 2.7 installed and in my windows path. Also, uninstalling from chocolately and installing the 2.0 release from the website stops any runtime errors.

**Comment by alleby** [comment] 2018-08-29 16:26
Hi, I experience the same issue, on 2 different windows 7 machines. One has python 3.6 installed, one has no python.
The problem does not happen when running preview, only when executing the clean.
I will try to pinpoint which option is problematic. Also I have bleachbit installed via chocolates, but I don't see how the install script could "damage" the files or anything.

**Comment by alleby** [comment] 2018-08-29 16:39
One option that makes a crash is the firefox cache:
![screenshot_18](https://user-images.githubusercontent.com/3751861/44802026-e50e8180-abba-11e8-8018-d8a083897584.png)

**Comment by alleby** [comment] 2018-08-29 16:49
So as suggested above, I uninstalled the chocolatey version (which should be the same anyway) and installed 2.0 windows from the bleachbit.org,  - problem gone. So I removed that one and installed using chocolatey again and the problem is still gone. I will report when I encounter more issues.

**Comment by az0** [comment] 2019-04-19 15:35
I counted several people's problems were resolved, so I am closing. If a person experiences this issue again, please open a new issue ticket.

**Closed by az0** 2019-04-19 15:35 UTC
Labels: not reproduced
