### ISSUE TITLE
BleachBit name on Windows 10 includes description

### ISSUE THREAD

**Issue by marsfan** [bleachbit/bleachbit#1134] opened 2021-03-10 21:08 UTC
**Describe the bug**
In the _Program Not Responding_ dialog, as well as the UAC prompt on Windows 10, the name for BleachBit includes a summary of the program. 

**To Reproduce**
There are two ways to reproduce this: 

Steps to reproduce the behavior (method 1):
1. Launch BleachBit as adminstrator
2. View name in User Access Prompt

Steps to reproduce the behavior (method 2):
1. Launch BleachBit
2.  Start a task that can cause BleachBit to freeze
3.  Attempt to interact with BleachBit when frozen to trigger _Program is not responding_ dialog. 

The error happens every time.

**Expected behavior**
The application name in the menus should just say _BleachBit_

**Screenshots**

This is how it appears in a _Program is not responding_ dialog. 
![image](https://user-images.githubusercontent.com/9311953/110694750-40675480-81a6-11eb-8b71-ffc05c75a2a9.png)

_Note:_ Windows does not allow taking screenshots of the UAC prompt, but the name is the same. 

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 version 20H2
 - BleachBit version 4.2.0

**Additional context**
It appears that the process to build BleachBit for Windows is setting the application name to the application name incorrectly. Instead of setting it to `APP_NAME` in setup.py, it is setting it to `APP_DESCRIPTION` in setup.py

**Comment by az0** [comment] 2021-03-12 04:11
This reminds me of https://github.com/bleachbit/bleachbit/issues/617 and maybe another issue. In any case, https://github.com/bleachbit/bleachbit/issues/848 may require a major rewrite of setup.py, so I would like to check back after that is done.

**Comment by rados** [comment] 2021-03-12 14:46
Seems like in our latest unstable build the name is correct. @Marsfan you can try it if you like:

https://ci.bleachbit.org/?prefix=dl/4.2.0.1833-master/

**Comment by Elaborendum** [comment] 2021-03-20 17:15
Then, #1109 Is a duplicate of this issue.

**Comment by abitrolly** [comment] 2022-11-06 18:38
Duplicate of #1000.

**Comment by az0** [comment] 2022-12-29 17:32
@marsfan 
Please see comment here https://github.com/bleachbit/bleachbit/issues/1109#issuecomment-1304874311

Please try that build and provide a new screenshot

**Comment by az0** [comment] 2023-01-07 17:26
For testing, the value can be shown a few ways
* Launch application, and the User Account Control prompt includes the text.
* Clean free disk space to cause non-responsiveness.
* Add the **Description** column to the details tab of the Task Manager applicaiton.

I tested with Windows 10 Pro 22H2, and the long description is gone in [build 2310](https://ci.bleachbit.org/?prefix=dl/4.4.2.2310-mkhon-python310/). It just shows the executable name instead.

It was coming from APP_DESCRIPTIN in the setup.py, but now this value is ignored.

**Closed by az0** 2023-01-07 17:26 UTC
Labels: platform: windows

**Comment by az0** [comment] 2023-02-04 22:07
I am splitting apart milestones 4.6 and 5.0 where 4.6 still has Python 3.4 and 5.0 has Python 3.10, which is not ready yet, and this issue goes with 5.0.

**Comment by az0** [comment] 2024-04-20 20:38
Two options to try for anyone having this issue

[Build 2584](https://ci.bleachbit.org/?prefix=dl/4.6.1.2584-processname/). This is the latest version of BleachBit (4.6.x) using the old framework (Python 3.4, GTK 3.24).

[Build 2467](https://ci.bleachbit.org/?prefix=dl/4.4.2.2467-mkhon-python310/) uses the new framework (Python 3.10.7), but it has an old build date July 2023. This build has known issues, so it's just for testing, so I recommend portable (zip) over installer (exe).  Once ready, this will be BleachBit 5.0.

Each build may have an improved process name in a different way.

Google Chrome may show safety warnings for the site ci.bleachbit.org . This is a false positive, but they won't give me details on the issue.

For cross referencing, here are related issues:  https://github.com/bleachbit/bleachbit/issues/617 https://github.com/bleachbit/bleachbit/issues/1000 https://github.com/bleachbit/bleachbit/issues/1109 https://github.com/bleachbit/bleachbit/issues/1134 https://github.com/bleachbit/bleachbit/issues/1655

**Comment by az0** [comment] 2024-08-26 04:19
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) has a fix for a shorter process name. If you still see an issue with the process name, reopen this issue.**

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.

**Comment by marsfan** [comment] 2024-12-10 05:31
Hey. Sorry, Somehow missed all of this. I just did a quick test on my computer. I'm running version 4.6.2 and everything looks good. No more long names!
