### ISSUE TITLE
Deletes Opera passwords on Win 10 (even if clear passwords is unticked for opera and chrome)

### ISSUE THREAD

**Issue by jasmine124** [bleachbit/bleachbit#1019] opened 2020-09-23 17:00 UTC
Hi, this has been happening with all releases of version 4 I have used, have 4.0.0 installed (and all latest versions of Opera (standard and GX) I have installed.

Installed on Win 10 Pro (though previously on Win 10 Home). Same on both.

**Comment by rados** [comment] 2021-05-10 12:39
@az0 
I can handle this one.

**Comment by rados** [comment] 2021-05-13 15:25
@jasmine124 
Could you please share some more details as I couldn't reproduce the issue? I tested on two Windows 10 machines and on both when I unchecked 'Passwords' under the 'Opera' section and cleaned (in Bleachbit app) the saved passwords in Opera browser were still there. You can see my screenshots and verify if I've done the right testing. You can share some screenshots as well.

![image](https://user-images.githubusercontent.com/332322/118147659-7d56fe00-b418-11eb-8b9f-33cbf67f5fbc.png)

**Comment by az0** [comment] 2021-06-22 03:44
@jasmine124 
Rados cannot reproduce the issue, so for now I will close this issue. If you have any information, please add a comment to this issue. We can reopen the issue if necessary.

**Closed by az0** 2021-06-22 03:44 UTC
Labels: invalid

**Comment by az0** [comment] 2026-08-09 01:58
FWIW:

- Today I made a change for the next release of the Winapp2.ini data file to show warnings when deleting passwords in any browser. 
- Since at least 2018, the Opera cleaner showed a warning when selecting the option to delete passwords.
- BleachBit 6 added many safeguards, such as requiring expert mode to bypass a warning.

Altogether, these are some changes to help users avoid unexpected deletion.
