### ISSUE TITLE
Recycle bin is emptied during preview

### ISSUE THREAD

**Issue by theatre-x** [bleachbit/bleachbit#170] opened 2017-01-10 19:05 UTC
Hey Andrew and fellow BB hackers,

I noticed this occur on a few different machines.
It seems as though in Windows 10 (I don't recall seeing this happen on any other version of Windows) that when I select to clean the Recycle Bin under the "System" category that when I hit the "Preview" button, the Recycle Bin gets emptied instead of previewed.

Do any of you experience this?
I don't currently have a log file of BB's operation to share since I just experienced this again without first recalling that I have experienced this action beforehand but once I get another chance, I will upload a log file.

Also, I'm using BB Portable off a flash-drive if that makes any bit of difference or means anything.

Cheers!

**Comment by az0** [comment] 2017-01-10 19:26
This is a duplicate of a closed issue with a fix released

https://bugs.launchpad.net/bleachbit/+bug/1648551

**Closed** 2017-01-11 04:50 UTC
