### ISSUE TITLE
Portable version shows string of import lang two times

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#674] opened 2019-11-06 05:10 UTC
The portable version shows the string of importing the language two times! See screenshot attached.

![2019-11-06 04_39_44-BleachBit (Keine Rückmeldung)](https://user-images.githubusercontent.com/11881073/68270011-28d10680-005c-11ea-86ee-cb868d5a1cbf.jpg)

**Comment by mkhon** [comment] 2020-04-02 18:59
Can not reproduce (latest master, ~3.9.0)

**Comment by az0** [comment] 2020-04-02 19:27
@Tobias-B-Besemer 

Do you still have this issue? Much has changed since November 2019, so I will close this. If you do have the issue, reopen the ticket please.

**Comment by mkhon** [comment] 2020-04-03 03:31
Minor issue (just incorrect logging). Fixed in #838

**Comment by az0** [comment] 2020-04-03 14:18
@Tobias-B-Besemer 
You can confirm the fix in any recent [CI build](https://ci.bleachbit.org/).

**Closed by az0** 2020-04-03 14:18 UTC
