### ISSUE TITLE
error de interfaz gráfica solo me salen cuadros

### ISSUE THREAD

**Issue by blacksong0194** [bleachbit/bleachbit#992] opened 2020-08-26 03:19 UTC
![Anotación 2020-08-25 231123](https://user-images.githubusercontent.com/70249290/91251395-5beaa080-e729-11ea-90ab-81a02a75dff5.jpg)

**Comment by az0** [comment] 2020-08-27 02:42
This is a duplicate of issue https://github.com/bleachbit/bleachbit/issues/901 . For a fix, please try the [latest CI build](https://ci.bleachbit.org/) (currently build 1708) or wait for the next beta or stable release.

**Closed by az0** 2020-08-27 02:42 UTC
