### ISSUE TITLE
No Such Table Error Message

### ISSUE THREAD

**Issue by justa-rowdy** [bleachbit/bleachbit#1429] opened 2022-11-20 22:29 UTC
No such table error messages

Currently using:  Forefox 107.0  (64-bit)  BleachBit 4.4.2

10/17/2022

Believe problem originally started occurring after updating to Firefox 104.0.2 (64-bit).
BleachBit 4.2.2.  Windows 10 Pro Version 21H2

Get the following (same or similar) error messages every time when running BleachBit.

Error: firefox.url_history: Function: Clean file: C:\Users\????????\Roaming\Mozilla\Firefox\Profiles\lu5es4xt.default\places.sqlite
Traceback (most recent call last):
File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: moz_places

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "bleachbit\Command.pyo", line 160, in execute
File "bleachbit\Special.pyo", line 313, in delete_mozilla_url_history
File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: moz_places: C:\Users\????????\AppData\Roaming\Mozilla\Firefox\Profiles\lu5es4xt.default\places.sqlite

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "bleachbit\Worker.pyo", line 87, in execute
File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

9/19/2022 - Completed the following.

Went into BleachBit Preferences and checked the box to Download and update cleaners from the community (winapp2.ini)
Resulted in same error reported in previous comment.

Downloaded the firefox.xml and replaced the one in the system cleaners directory.
Resulted in same error reported in previous comment.

Searched Firefox directory on "places.sqlite"
    Resulted in two matches.
    a. C:\Users\????????\AppData\Roaming\Mozilla\Firefox\Profiles\6xdcjkfn.default-release
    b. C:\Users\????????\AppData\Roaming\Mozilla\Firefox\Profiles\lu5es4xt.default

The "places.sqlite" file is in two different directories under Firefox Profiles.

**Comment by justa-rowdy** [comment] 2022-11-20 22:41
Confirmed same error messages are still present.

**Comment by justa-rowdy** [comment] 2022-11-21 01:12
Investigated further and it appears the error messages are a result of having two Firefox profiles.
Was able to determine that I did not need or use one of the profiles.
After backing them up to another folder, deleted the profile "lu5es4xt.default" from both the Local and Roaming directories.
Closed everything and restarted PC.
Opened Firefox and the desired profile "6xdcjkfn.default-release" was active and appeared to be working properly. 
Running BleachBit resulted in no error messages being displayed.

I may have resolved the error messages, but it appears there is still an issue present that produces error messages when there are multiple Firefox profiles and/or related circumstances.

**Comment by rados** [comment] 2022-11-21 05:53
@justa-rowdy, thank you, this is really helpful. I will trace it.

**Comment by abitrolly** [comment] 2022-11-21 14:31
A duplicate of #1423.

**Comment by justa-rowdy** [comment] 2022-11-21 16:16
This was originally/wrongly submitted under #1397. AZiem requested to make it a separate issue with this assigned No Such Table title. Unfortunately, the investigation I performed is the most I am able to technically contribute.  My specific issue is now resolved. However, the "real" issue is not. Please combine or close this as you see fit.

**Comment by az0** [comment] 2022-11-27 20:53
Yes, this looks like #1423 but not like #1397. I would keep #1423 open if @justa-rowdy  were able to reproduce it still, but he cannot, so let's close it.

This error is not seen with this configuration

Ubuntu 22.04
Firefox 107.0 (64-bit)
BleachBit: latest from git

multiple profiles

$ python3 bleachbit.py  -c firefox.url_history  |grep plac
Clean file 0B /home/username/snap/firefox/common/.mozilla/firefox/61oxny3k.default-release-1//places.sqlite
Clean file 0B /home/username/snap/firefox/common/.mozilla/firefox/gppelwcw.default-release//places.sqlite
Clean file 0B /home/username/snap/firefox/common/.mozilla/firefox/uo7q506n.dev-edition-default//places.sqlite
Clean file 0B /home/username/snap/firefox/common/.mozilla/firefox/omqh2oui.test_profile//places.sqlite
Clean file 0B /home/username/.mozilla/firefox/61oxny3k.default-release-1//places.sqlite
Clean file 0B /home/username/.mozilla/firefox/gppelwcw.default-release//places.sqlite
Clean file 0B /home/username/.mozilla/firefox/uo7q506n.dev-edition-default//places.sqlite

**Comment by az0** [comment] 2023-01-02 00:30
@justa-rowdy 

Two things

First, a few people have reported this, but I haven't been able to naturally reproduce it, so would you be willing to privately send me a copy of your file `C:\Users\s-tro\AppData\Roaming\Mozilla\Firefox\Profiles\ihkv64ph.default\places.sqlite` to my email ahz001 at gmail dot com?

Second, would you please test [build 2307](https://ci.bleachbit.org/?prefix=dl/4.4.2.2307-moz_no_places/)? It has a special fix that is not in the main-line code yet. Note: it will modify the places.sqlite file, but it is okay to send the file after cleaning it.

**Comment by justa-rowdy** [comment] 2023-01-05 15:42
The backup I made of the 2nd Firefox profile causing the issue was deleted and unrecoverable.  Still, no longer get the error messages since deleting the 2nd unneeded profile.  Need to check a portable disk, but not confident the file is on there either,
Currently using BleachBit version 4.4.2, Build number 2142
I can checkout build 2307, but without the deleted 2nd profile it may not be helpful?

**Comment by az0** [comment] 2023-02-04 21:14
>Currently using BleachBit version 4.4.2, Build number 2142 I can checkout build 2307, but without the deleted 2nd profile it may not be helpful?

Yes, it may not be helpful. Thank you for the reply, though.

**Comment by az0** [comment] 2023-02-04 21:16
>but without the deleted 2nd profile it may not be helpful?

It will not be helpful to check that your error does not happen, but please check whether I broke something while trying to fix it (i.e., a regression). You should get no error, and Firefox should be thoroughly cleaned.

I merged in the fix into the master branch, so now you can test master build 2377 or later on the [CI Build site](https://ci.bleachbit.org/).

**Comment by justa-rowdy** [comment] 2023-02-04 23:42
Pulled BleachBit-4.4.2.2378-portable.zip from the CI Build site.  Extracted to a new folder in Downloads. Assuming since it is the portable version I could run it directly from the new folder without have to uninstall my current version.

Windows 10 Pro Version 10.0.19045 64bit
Firefox 109.0.1 (64-bit)
Bleachbit: 4.4.2.2378

Ran bleachbit.exe from the folder
Verified that Version 4.4.2.2378 was running by displaying system information.
Selected all of the Firefox areas to clean. And most of the other applications/scans with few exceptions and hit Clean.

Executed with no errors and appeared to clean Firefox.

Still need to perform additional verification to validate cleaning.

**Comment by az0** [comment] 2023-02-05 17:30
Thank you for testing

> Still need to perform additional verification to validate cleaning.

The main concern is the checkbox **Firefox -** **URL History**. It should clean the URL history, but not bookmarks.

**Comment by justa-rowdy** [comment] 2023-02-09 23:19
I have Display Firefox History turned off as my normal running state (Firefox doesn't display history, but it is still logging in the profile). For that reason I wanted to take a closer look at the files being cleaned in the profile. Basically, have a starting point where I thought the profile files were empty of browsing data by looking at file sizes. Perform some browsing and note the changed file sizes. Then clean and compare the results with the starting point. 

I was able to do this and I am confident that Bleachbit: 4.4.2.2378 is cleaning. My Bookmarks were unaffected.

**Comment by az0** [comment] 2023-05-15 23:43
@justa-rowdy 

Thank you for confirming this works

**Closed by az0** 2023-05-15 23:43 UTC
Labels: not reproduced, platform: windows

**Comment by az0** [comment] 2023-09-11 03:04
[BleachBit version 4.5.0 beta ](https://www.bleachbit.org/news/bleachbit-450-beta) has this fix for Firefox "no such table"
