### ISSUE TITLE
Can't shred using right click context menu option with Bleachbit 4.4.0 in Windows 10

### ISSUE THREAD

**Issue by tlhulse** [bleachbit/bleachbit#1227] opened 2021-07-14 17:17 UTC
**Describe the bug**
Attempting to shred any file or folder using the "Shred with Bleachbit" right click/context menu option leads to an error and does not shred the file/folder.

**To Reproduce**
1. Create folder C:\Test and create an empty text file named Test.txt in the folder. (C:\Test\Test.txt) 
2. Open C:\Test in explorer
3. Right click on Test.txt file and select "Shred with Bleachbit"
4. Observe Bleachbit open with an error displayed (shown below and in screenshot) and a Delete Confirmation box
5. Click Delete in the Delete Confirmation Box
6. Observe Bleachbit close and the file C:\Test\Test.txt has not deleted.

The error:
Error: _gui.files: Command to shred C:\Test\"C:\Test\Test.txt"
Traceback (most recent call last):
File "bleachbit\Worker.pyo", line 87, in execute
File "bleachbit\Command.pyo", line 79, in execute
File "bleachbit\FileUtilities.pyo", line 558, in getsize
pywintypes.error: (123, 'FindFirstFileW", 'The filename, directory name, or volume label syntax is incorrect.')

*Note: The error happens every time and with any file or folder.

**Expected behavior**
1. Create folder C:\Test and create an empty text file named Test.txt in the folder. (C:\Test\Test.txt)
2. Open C:\Test in explorer
3. Right click on Test.txt and select "Shred with Bleachbit"
4. Observe Bleachbit open with no errors displayed and a Delete Confirmation box
5. Click delete in the Delete Confirmation Box
6. Bleachbit closes and C:\Test\Test.txt has been deleted/shredded.

**Screenshots**
![BleachbitShredError](https://user-images.githubusercontent.com/11636260/125663956-ff0da5b3-6e3b-4c1f-b268-8a5a4be88834.jpg)

**Desktop (please complete the following information):**
OS: Windows 10 Pro, Version 21H1, Build 19043.1083
BleachBit Version: 4.4.0, Fresh Install with default settings

**Additional context**

**Comment by rados** [comment] 2021-07-23 14:03
@tlhulse
This is really interesting. I couldn't reproduce it on my Windows 10 machine with Bleachbit 4.4.0. Could you share your Windows and Bleachbit versions?

**Comment by tlhulse** [comment] 2021-07-28 00:17
@rados 
Sure.

Windows 10 Pro 64-bit - Version 21H1 (Windows 10 May 2021 Update) - OS build 19043.1110
BleachBit 4.4.0 - Build 1929

*Note: I also have the exact same issue on my laptop which runs Windows 10 Home 64-bit with the same version and build as the Pro version listed above.

Here are screenshots of my Windows and BleachBit Specifications in case they provide additional needed information.
![SysInfo_Desktop_Windows](https://user-images.githubusercontent.com/11636260/127243635-1f0ed4cd-af26-4074-9d13-4c2238440aed.jpg)
![Version_Desktop_Bleach](https://user-images.githubusercontent.com/11636260/127243665-0e411b12-7d5d-4bc7-8091-46056ac04e46.jpg)
![SysInfo_Desktop_Bleach](https://user-images.githubusercontent.com/11636260/127243691-3a25ffda-aae5-4e37-ab6f-4df544637a59.jpg)

**Comment by rados** [comment] 2021-07-28 22:42
@tlhulse 
Thank you. I think I have a clue. If you remove completely Bleachibit, reboot and install Bleachbit it could help. Please share the results.

**Comment by cdt9681** [comment] 2021-07-29 08:15
@rados 
Performed a standard uninstall then rebooted computer and performed fresh install of bleachbit (BleachBit-4.4.0-setup.exe from https://www.bleachbit.org/download/windows).  No change, the same error occurs.

I then performed an uninstall using Revo Uninstaller to make sure there weren't any files or registry folders left over then rebooted computer and performed a fresh install again.  Still receiving the same error.

**Comment by tlhulse** [comment] 2021-07-29 08:16
@rados
Performed a standard uninstall then rebooted computer and performed fresh install of bleachbit (BleachBit-4.4.0-setup.exe from https://www.bleachbit.org/download/windows). No change, the same error occurs.

I then performed an uninstall using Revo Uninstaller to make sure there weren't any files or registry folders left over then rebooted computer and performed a fresh install again. Still receiving the same error.

**Comment by tlhulse** [comment] 2021-07-29 17:31
@rados 
Well, I figured out what's causing the error to occur.  

I have UAC disabled through the registry on both my desktop and laptop computers. I re-enabled it via the command line with "reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 1 /f" then rebooted and now the error no longer appears and I am able to successfully shred from the context menu.

**Comment by az0** [comment] 2021-07-29 22:08
> I have UAC disabled
@tlhulse 
Shredding is more accurate when BleachBit has access to certain Windows APIs that require administrator privileges, so I recommend allowing BleachBit to have the privileges for this use. When BleachBit is started without them, it should start with a warning about this in the log window.

Likewise, Microsoft (in the [EnableLUA documentation](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-lua-settings-enablelua)) recommends not disabling the UAC

>We do not recommend using this setting

So, are you okay closing this issue?

**Comment by rados** [comment] 2021-07-31 17:02
@tlhulse 
You can check my comment in #1238 and try the same thing with your UAC disabled.

**Comment by tlhulse** [comment] 2021-08-01 07:10
@rados 
Yes, changing the triple quotes to single quotes in that registry entry resolved the error on both my computers.  Thank you.

**Closed** 2021-09-06 23:56 UTC
