### ISSUE TITLE
BleachBit 3.0 portable RunDLL error on Windows 10 Home

### ISSUE THREAD

**Issue by somedude305** [bleachbit/bleachbit#734] opened 2019-12-21 22:00 UTC
My Windows 10 version is build 18362.19h1_release.190318-1202, which as of writing is the latest Windows 10 version for Home edition.

So I go and download BleachBit from bleachbit.org. I extract the portable zip with 7Zip, and then I go into the folder and double click bleachbit.exe. I get a UAC prompt, hit yes and then I get an error message. This error message is a popup box and the title is "RunDLL". The message says "There was a problem starting X:\Y\[Run The specified module could not be found." (directory obviously spoofed for writing's sake) Then about 3 seconds later I get the GUI for the program and it looks normal? But I don't want to touch it as I'm not sure if it the program is functional due to the error. The interesting thing is this error box says it was trying to start something from X:\Y when the BleachBit folder is located at X:\Y\Z.

So, what's happening? Is the program stable to run, what does this error mean? Using an alternative for now. I do not have any real-time antimalware enabled btw.

**Comment by az0** [comment] 2019-12-22 19:08
This is not a common error for BleachBit. I did a Google search, and it happens with various other Windows application. It looks like the Windows registry is corrupt or misconfigured.

Here's a Google search: [RunDLL "there was a problem starting" "module could not be found"](https://www.google.com/search?q=RunDLL+%22there+was+a+problem+starting%22+%22module+could+not+be+found%22). Look at a few pages, and consider their solutions. 

Did you put BleachBit on a removable or network drive? You could also try a local drive.

You can test BleachBit "safely" by trying a preview. If it can do this, it's likely functional.  

Another basic test is this: First, make a copy of a file. Second, to use the "Shred Files" option to delete the copy.

Let me know how it goes.

**Comment by somedude305** [comment] 2019-12-29 11:42
> This is not a common error for BleachBit. I did a Google search, and it happens with various other Windows application. It looks like the Windows registry is corrupt or misconfigured.
> 
> Here's a Google search: [RunDLL "there was a problem starting" "module could not be found"](https://www.google.com/search?q=RunDLL+%22there+was+a+problem+starting%22+%22module+could+not+be+found%22). Look at a few pages, and consider their solutions.
> 
> Did you put BleachBit on a removable or network drive? You could also try a local drive.
> 
> You can test BleachBit "safely" by trying a preview. If it can do this, it's likely functional.
> 
> Another basic test is this: First, make a copy of a file. Second, to use the "Shred Files" option to delete the copy.
> 
> Let me know how it goes.

Damn, guess I need to check out my registry. I did put the files on a removable VeraCrypt disk. I tried to do basic functions with the software and they all worked perfectly. Did a full clean and it worked too, so I think the software is working fine, there's just an error popup every time I open, which isn't a big deal to me

**Comment by az0** [comment] 2020-01-04 23:15
(1) I hear it's basically working and  (2) I can't reproduce it, so I am going to close the issue.

**Closed by az0** 2020-01-04 23:15 UTC
