### ISSUE TITLE
BleachBit should save position on Windows

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#423] opened 2018-12-20 00:50 UTC
IMHO BleachBit should save position on Windows.

Means: I normally work 'maximized', but after each start of BleachBit, the Window have it old size again.

**Comment by az0** [comment] 2018-12-25 17:15
Duplicate of https://github.com/bleachbit/bleachbit/issues/204

**Closed by az0** 2018-12-25 17:15 UTC
Labels: enhancement
