### ISSUE TITLE
Confirm before delete broken

### ISSUE THREAD

**Issue by ghost** [bleachbit/bleachbit#844] opened 2020-04-03 16:26 UTC
when deselecting confirm before delete and going to delete a item it still confirms the deletion.

**Comment by az0** [comment] 2020-04-05 14:30
When you delete an item, are you using the big "Clean" button on the toolbar? 

Or do you right click on an item and choose "Clean" from the context (pop-up) menu? 

Or some other way?

**Comment by silentshotghost** [comment] 2020-04-05 14:32
right click a file then press "shred with bleachbit"

**Comment by peter-marshall** [comment] 2020-05-12 16:03
I'll work on this one.

**Comment by az0** [comment] 2020-08-26 03:45
I couldn't reproduce this because first I ran into a worse issue https://github.com/bleachbit/bleachbit/issues/993

@ghost

As a workaround, try this

1. Open BleachBit
1. In Windows Explorer, find the file you want to shred
1. Drag the file from Windows Explorer onto BleachBit

Alternatively

1. Copy file from Windows Explorer
1. In BleachBit, click application menu (top right corner)
2. Click _Shred files from clipboard_

**Comment by rados** [comment] 2020-12-18 17:52
@az0 
I can finish this one.

**Comment by rados** [comment] 2020-12-22 20:47
@az0 
Reproduced it. In cb_run_option function we don't check for delete_confirmation property and call the confirmation dialog every time. Could it be intentional?

Also I've noticed another possible issue. When the app is running and I right click over a file in Explorer and execute the context menu command "shred with bleachbit" the Bleachbit main window come to front but never executes the shred command itself. I think this should be fixed...

**Comment by az0** [comment] 2020-12-22 20:56
> @az0
> Reproduced it. In cb_run_option function we don't check for delete_confirmation property and call the confirmation dialog every time. Could it be intentional?

No, it's not intentional, and the same problem is in `shred_paths`.
 
> Also I've noticed another possible issue. When the app is running and I right click over a file in Explorer and execute the context menu command "shred with bleachbit" the Bleachbit main window come to front but never executes the shred command itself. I think this should be fixed...

Good catch. Feel free to create a new issue ticket.

**Closed** 2021-01-30 22:09 UTC
Labels: priority:high

**Comment by az0** [comment] 2021-01-30 22:11
The account of the user who reported this was deleted, so I can't ask him to test, but it's fixed now.
