### ISSUE TITLE
Does not clear Cache or History for Firefox 70 [Bleachbit 3.0 Portable on Windows]

### ISSUE THREAD

**Issue by ReeceN** [bleachbit/bleachbit#660] opened 2019-10-31 09:05 UTC
Bleachbit 3.0 (tested with Portable version) does not clear Firefox 70's Cache or History.

Note: The winapp2.ini option is used.

**Comment by Tobias-B-Besemer** [comment] 2019-11-05 03:37
@ReeceN, can you do me a favor, download the following file and replace the existing firefox.xml with it? Then start BB and make a new try...

https://raw.githubusercontent.com/bleachbit/bleachbit/3f976fd13b06db8aa8adccf788260923a1855022/cleaners/firefox.xml

**Comment by ReeceN** [comment] 2019-11-05 08:25
@Tobias-B-Besemer Replaced \BleachBit-Portable\share\cleaners\firefox.xml with that version however both History and Cache remains.

BleachBit 2.2 seems to work fine.

Note following directory contains over 1GB after cleaning attempt.
\AppData\Local\Mozilla\Firefox\Profiles\

**Comment by Tobias-B-Besemer** [comment] 2019-11-06 00:02
@ReeceN, which language do you use?
Maybe a translation prob...
Do you see "Cache" as option of other progs ???

**Comment by ReeceN** [comment] 2019-11-06 00:35
@Tobias-B-Besemer I didn't know that you can change the langauge. It's English.

No there is no Cache option for Chrome either.

In BleachBit 2.2 there is for both.

**Comment by Tobias-B-Besemer** [comment] 2019-11-06 02:09
@ReeceN, language gets taken from your Windows...

...seems is no prob from the Fx cleaner, seems to be something else...

Can you have a look in BB2.2 if there are a other prog beside Chrome and Fx were you can clean cache and then look in BB3.0 if there is cache as option missing, too?

You use BB3.0 stable right?

Can you install BB3.0 on you system and look if the option is missing there, too?

**Comment by Tobias-B-Besemer** [comment] 2019-11-06 02:25
@ReeceN, I guess you have US English, right?

**Comment by Tobias-B-Besemer** [comment] 2019-11-06 05:13
Tested BB3.0 portable on Win7 64-bit in German. Cache Cleaning is shown...

**Comment by ReeceN** [comment] 2019-11-06 09:09
I use English UK.

- Firefox
- Chrome
- Opera

Are what used to have the options for Cache.

I installed the English US language pack through Windows settings, restarted machine, re-extracted the BB3 Portable and launched it. It then correctly showed the Cache options.

I also tried the installer version after the language pack install and that also works fine.

The old BB3 Portable still does not update to show the Cache options however.

The hash of both BB3 Portable zip files are the same.

Maybe it was the language or maybe it was a faulty .zip extraction.

**Comment by Tobias-B-Besemer** [comment] 2019-11-06 09:15
@ReeceN, thank you very much! :)

You can try one more think, if you like:
Switch your Windows back to UK English, extract BB into a new folder and start it again.
Does the Cache options now come up, too?

**Comment by ReeceN** [comment] 2019-11-06 09:47
@Tobias-B-Besemer 

Switched back to Eng UK, uninstalled Eng US and restarted.

Extracting the BB3 Portable zip into new directory continues to show the correct Cache options.

**Comment by Tobias-B-Besemer** [comment] 2019-11-06 14:10
OK, so it seems you had an unreproducible issue that is now solved, right?
So we can close this issue ticket here?

**Comment by ReeceN** [comment] 2019-11-06 14:24
Yup feel free. :)

Thanks for the help!

**Comment by Tobias-B-Besemer** [comment] 2019-11-06 15:02
You're welcome! :-)

**Comment by Tobias-B-Besemer** [comment] 2019-12-03 15:21
@az0, close this ussue, now ???

**Comment by az0** [comment] 2019-12-05 01:01
@Tobias-B-Besemer 
OK

**Closed by az0** 2019-12-05 01:01 UTC
Labels: insufficient cleaning
