### ISSUE TITLE
Fontconfig error: Cannot load default config file on Windows 10

### ISSUE THREAD

**Issue by mayerthomas** [bleachbit/bleachbit#901] opened 2020-04-29 12:31 UTC
When I start BleachBit on my Windows-10-Machine, instead of text i only see rectangles in the application.
Starting via BleachBit-Debugging-Terminal brings the following error:
Fontconfig error: Cannot load default config file

![Anmerkung 2020-04-29 143228](https://user-images.githubusercontent.com/19205702/80596202-489f2100-8a26-11ea-9a4d-8a11b99095fd.jpg)

**Comment by az0** [comment] 2020-05-02 14:42
@mayerthomas 

Is your Windows system set to English?  If not, which language is it?

**Comment by crop211** [comment] 2020-05-12 00:23
I also have this problem. Bleachbit will not show fonts. Only rectangles

Attached are a screenshot showing Bleachbit display and Bleachbit log.

![2020-05-12_09h49_05](https://user-images.githubusercontent.com/63181179/81624530-e65efc80-93e5-11ea-99b4-388a9f3dc712.png)


[bleachbit.log](https://github.com/bleachbit/bleachbit/files/4612723/bleachbit.log)

.
This has been occuring for a long time. It happened with version 3.0 about 4 months ago which caused me to uninstall Bleachbit. Now after trying version 4.0 it still occurs. Every other program works perfectly, only Bleachbit has this error.

This on Win10 set to english US + english AU.

Looks like I'll have to give up and uninstall again. Pity, I love Bleachbit on Linux on the same PC.

Bleachbit Log :

BleachBit version 4.0.0
Build number 1628
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = False
SQLite version 3.31.1
local_cleaners_dir = None
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
options_dir = C:\Users\admin\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\admin\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_AU', 'cp1252')
os.getenv('APPDATA') = C:\Users\admin\AppData\Roaming
os.getenv('cd') = C:\Program Files (x86)\BleachBit
os.getenv('LocalAppData') = C:\Users\admin\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\admin\AppData\LocalLow
os.getenv('Music') = C:\Users\admin\Music
os.getenv('USERPROFILE') = C:\Users\admin
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\admin\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\admin
platform.win32_ver[1]() = 10.0.18362
platform.platform = Windows-10-10.0.18362
platform.version = 10.0.18362
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\bleachbit_console.exe', '--gui', '--debug-log=C:\\Users\\admin\\desktop\\bleachbit.log']
sys.executable = C:\Program Files (x86)\BleachBit\bleachbit_console.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = False
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\Diagnostic.pyo
BleachBit version 4.0.0
Build number 1628
GTK version 3.18.9
GTK theme = Adwaita
GTK icon theme = Adwaita
GTK prefer dark theme = False
SQLite version 3.31.1
local_cleaners_dir = None
locale_dir = C:\Program Files (x86)\BleachBit\share\locale\
options_dir = C:\Users\admin\AppData\Roaming\BleachBit
personal_cleaners_dir = C:\Users\admin\AppData\Roaming\BleachBit\cleaners
system_cleaners_dir = C:\Program Files (x86)\BleachBit\share\cleaners\
locale.getdefaultlocale = ('en_AU', 'cp1252')
os.getenv('APPDATA') = C:\Users\admin\AppData\Roaming
os.getenv('cd') = C:\Program Files (x86)\BleachBit
os.getenv('LocalAppData') = C:\Users\admin\AppData\Local
os.getenv('LocalAppDataLow') = C:\Users\admin\AppData\LocalLow
os.getenv('Music') = C:\Users\admin\Music
os.getenv('USERPROFILE') = C:\Users\admin
os.getenv('ProgramFiles') = C:\Program Files (x86)
os.getenv('ProgramW6432') = C:\Program Files
os.getenv('TMP') = C:\Users\admin\AppData\Local\Temp
os.path.expanduser('~') = C:\Users\admin
platform.win32_ver[1]() = 10.0.18362
platform.platform = Windows-10-10.0.18362
platform.version = 10.0.18362
sys.argv = ['C:\\Program Files (x86)\\BleachBit\\bleachbit_console.exe', '--gui', '--no-uac', '--gui', '--debug-log=C:\\Users\\admin\\desktop\\bleachbit.log']
sys.executable = C:\Program Files (x86)\BleachBit\bleachbit_console.exe
sys.version = 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)]
win32com.shell.shell.IsUserAnAdmin() = True
__file__ = C:\Program Files (x86)\BleachBit\library.zip\bleachbit\Diagnostic.pyo

**Comment by crop211** [comment] 2020-05-12 00:46
Just thought I'd add.

Bleachbit Portable produces the same Error.

This is the output of the Bleachbit Debugging Terminal.

Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
closest monitor (0) geometry = (0, 0)+(1366, 768), window geometry = (283, 84)+(800, 600)
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file.

**Comment by mkhon** [comment] 2020-06-25 17:13
@mayerthomas @crop211 Do you by any chance have FONTCONFIG_FILE or FONTCONFIG_PATH environment variables?
You can check that by opening cmd.exe and running

echo %FONTCONFIG_FILE%
echo %FONTCONFIG_PATH%

**Comment by mkhon** [comment] 2020-06-25 17:26
I can reproduce this when I set FONTCONFIG_FILE to some non-existent path (or invalid fonts.conf)

**Comment by az0** [comment] 2020-06-26 04:19
@mayerthomas 
@crop211 

There is a fix available that may help with this. Would you please try version [build 4.0.1.1666](https://ci.appveyor.com/project/az0/bleachbit/builds/33740816/artifacts)? (Right now, the fix is only in this build 1666.) After testing, please write a comment here to let us know how it went.

**Comment by mayerthomas** [comment] 2020-06-26 06:14
A view days ago I reinstalled windows. Bleachbit no works as expected.
I'm very sorry that I can't help anymore on this issue.

**Comment by crop211** [comment] 2020-06-27 04:41
Dear Andrew,

Thanks for your Bleachbit update 4.0.1.1666.

I installed it and it now works perfectly. Great to have bleachbit back. Much appreciated.


Thanks Max,

Here are the results of your suggested tests :

C:\Users\admin>echo %FONTCONFIG_FILE%   returns   C:\Windows\fonts.conf

C:\Users\admin>echo %FONTCONFIG_PATH%   returns   C:\Users\admin>

The only fonts.conf files on my PC are in program folders e.g Geany, GPG4Win, Gajim etc. None at C:\Users\admin> or C:\Windows.

There is of course a fonts directory at C:\Windows\Fonts.

I have never adjusted the %PATH%.

**Comment by crop211** [comment] 2020-06-27 04:43
Dear Andrew,

Thanks for your Bleachbit update 4.0.1.1666.

I installed it and it now works perfectly. Great to have bleachbit back. Much appreciated.

Yours, crop211

June 26, 2020 6:19:40 AM CEST Andrew Ziem <notifications@github.com> wrote:

@mayerthomas
@crop211
There is a fix available that may help with this. Would you please try version build 4.0.1.1666? (Right now, the fix is only in this build 1666.) After testing, please write a comment here to let us know how it went.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.[{"@context": "http://schema.org","@type": "EmailMessage","potentialAction": {"@type": "ViewAction","target": "https://github.com/bleachbit/bleachbit/issues/901#issuecomment-649952763","url": "https://github.com/bleachbit/bleachbit/issues/901#issuecomment-649952763","name": "View Issue"},"description": "View this Issue on GitHub","publisher": {"@type": "Organization","name": "GitHub","url": "https://github.com"}}]

******

DO NOT let THEM read and record your personal messages or calls!

Many Private/Secure communication options available.

Preferred & Safest : SIGNAL (Voice, SMS, text, video, files).

IM : Telegram, Ricochet, etc.
Matrix : Riot,  etc.
XMPP : Gajim, etc.
Secure Email : Protonmail, Elude (Tor only ), etc.
Temporary Emails.
PGP encryption.

Or suggest an alternative.

******

**Comment by az0** [comment] 2020-07-05 17:16
> A view days ago I reinstalled windows. Bleachbit no works as expected.
> At the moment, there is no FONTCONFIG_FILE or FONTCONFIG_PATH set on my machine.
> I'm very sorry that I can't help anymore on this issue.

@mayerthomas 

Thank you still for getting back to me

> I installed it and it now works perfectly. Great to have bleachbit back. Much appreciated.
@crop211 
Thank you for testing and for confirming.

I hear this is fixed, so I am closing it.

**Closed by az0** 2020-07-05 17:16 UTC
Labels: bug
