### ISSUE TITLE
Shredding files and folders sometimes leaves remnants.

### ISSUE THREAD

**Issue by StaticallyTypedRice** [bleachbit/bleachbit#503] opened 2019-03-21 18:17 UTC
# Issue

This is present on *at least* BleachBit 2.0.

When shredding a file or (especially) a folder, or when cleaning with the "overwrite files" setting enabled, BleachBit sometimes leaves behind artifacts such as files and folders renamed to random names such as one or two random letters and/or numbers, or folders and empty files with the original name. I don't remember if I've ever also seen it leave behind unshredded or partially shredded files, but I have that suspicion. I've observed this on both Windows and Linux.

Usually, no errors are thrown when this happens.

This becomes a problem for obvious security reasons, but is also annoying in that app data and temporary directories fill up with these unshredded or undeleted artifacts with nonsensical names (as they are never deleted and build up over time), which is a hassle if you ever actually need to find something in those directories. 

# Reproducing

It's hard to definitively reproduce this problem because it happens intermittantly and seemingly randomly, but if you shred a lot of folders, you are likely to see this problem at some point.

If you have been using BleachBit with the "overwrite" function enabled for a while, look in some of the directories that BleachBit shreds while cleaning, especially custom directories, you may see lots of nonsensical folders.

**Comment by Jon-guy30** [comment] 2019-03-28 11:33
I don't seem to have this problem. I just deleted a bunch of stuff in appdata temporary files folder, I've also been shredding files and overwriting information and there have been no remnants. Also in the downloads directory, there's nothing. 

Is it always the same folders where bleachbit cleans them? 

This seems like an urgent bug and should be looked into.

**Comment by StaticallyTypedRice** [comment] 2019-03-29 16:23
>Is it always the same folders where bleachbit cleans them?

It happens seemingly randomly for me (and not too often), and I haven't noticed a pattern of which folders are left behind. I'll look out for it the next time I use bleachbit and see if I can find any patterns.

**Comment by az0** [comment] 2019-04-19 15:23
I am not able to reproduce it. Can you think of anything that would help reproduce it?

In one test on Linux (Ubuntu 18.10 with ext4 filesystem) I deleted 1000 folders and files, which I attached here in case you want to test. No folder or file was left behind.
[manyfolders.zip](https://github.com/bleachbit/bleachbit/files/3098508/manyfolders.zip)

Make sure not to kill the BleachBit process before it is done. 

About Windows: Is it Windows 10? Is it a fixed drive with a NTFS file system (which is common for C: )? Do you have any antivirus/security software running that could block BleachBit?

**Comment by StaticallyTypedRice** [comment] 2019-04-19 18:54
The next time I see it I will make more observations and update.

> Is it Windows 10?

Yes

> Is it a fixed drive with a NTFS file system (which is common for C: )?

Yes, though I believe I've seen it on NTFS removable drives too.

> Do you have any antivirus/security software running that could block BleachBit?

Only Windows Defender which doesn't complain about BleachBit.

**Comment by az0** [comment] 2019-04-19 20:06
There is some chance Windows Defender is locking the file or folder temporary to scan it, so this prevents BleachBit from finishing its job. If this were true, Windows Defender would not complain because the file is probably safe.

You could maybe see more error/debug messages by running the console version `c:\program files (x86)\BleachBit\bleachbit_console.exe`  If you do see a related message there, please include it here

**Comment by StaticallyTypedRice** [comment] 2019-04-20 04:43
I'll look out for errors the next time I shred something and update when I find something!

**Comment by az0** [comment] 2019-06-06 03:44
You asked about "BleachBit console for Linux." Yes, in a terminal run:

`python bleachbit.py --debug-log=/tmp/bleachbit.log --gui`

or

`bleachbit --debug-log=/tmp/bleachbit.log --gui`

You wrote "update when I find something." Maybe this has not happened since April 19, so I will close it for now. If the same issue happens, reopen this ticket.

**Closed by az0** 2019-06-06 03:44 UTC
