### ISSUE TITLE
missing clean icon

### ISSUE THREAD

**Issue by saiballo** [bleachbit/bleachbit#799] opened 2020-02-28 19:44 UTC
hi, 
bleachbit 3.2.0 installed from site hasn't clean icon on the top menu. see screenshot
![Schermata a 2020-02-28 20-42-49](https://user-images.githubusercontent.com/3473910/75582098-20696500-5a6b-11ea-88b1-25b7db69ff09.png)

**Comment by ediowar** [comment] 2020-02-29 00:38
![Clean](https://user-images.githubusercontent.com/44164186/75597020-1192aa80-5a8b-11ea-905e-5e091302e9d7.png) -- is clean icon for Ubuntu (Mint).

**Comment by az0** [comment] 2020-03-02 01:10
For the toolbar, BleachBit uses the GTK stock icons.

- preview: edit-find
- clean: edit-clear-all
- stop: process-top

It seems your themes are missing the icon. When the stock icon is not found, GTK replaces it with the broken icon.

Today I added related diagnostic information. From the command line, it looks like this

```
$ python3 bleachbit.py  --sysinfo
BleachBit version 3.9.0
GTK version 3.24.12
GTK theme = Yaru
GTK icon theme = Yaru
GTK prefer dark theme = False
SQLite version 3.29.0
[...snip...]
platform.linux_distribution() = ('Ubuntu', '19.10', 'eoan')
```
This info is also available from the GUI: click in the menu on "Diagnostics." Would either of you show me the lines from your system, but like above?

If you would like an RPM package instead of [running it from Git](https://docs.bleachbit.org/dev/running-from-source-code.html), let me know.

**Comment by saiballo** [comment] 2020-03-02 07:26
this is my:

BleachBit version 3.2.0
Git revision 2e9c779a
GTK version 3.22.30
SQLite version 3.22.0
FSE = UTF-8
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /root/.config/bleachbit
personal_cleaners_dir = /root/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('it_IT', 'UTF-8')
os.getenv('DESKTOP_SESSION') = None
os.getenv('LOGNAME') = root
os.getenv('USER') = root
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /root
platform.linux_distribution() = ('LinuxMint', '19.3', 'tricia')
platform.platform = Linux-4.15.0-88-generic-x86_64-with-LinuxMint-19.3-tricia
platform.version = #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python2
sys.version = 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0]
__file__ = /usr/share/bleachbit/Diagnostic.py

**Comment by ediowar** [comment] 2020-03-02 07:39
```
BleachBit version 3.9.0
GTK version 3.18.9
GTK theme = Ambiance
GTK icon theme = ubuntu-mono-dark
GTK prefer dark theme = True
platform.linux_distribution() = ('Ubuntu', '16.04', 'xenial')
```

**Comment by az0** [comment] 2020-03-08 20:03
> `Today I added related diagnostic information.`
> Where to?
> 
> ```
> BleachBit version 3.9.0
> GTK version 3.18.9
> GTK theme = Ambiance
> GTK icon theme = ubuntu-mono-dark
> GTK prefer dark theme = True
> platform.linux_distribution() = ('Ubuntu', '16.04', 'xenial')
> ```

That's the relevant information, so I can try to reproduce it with the same icon theme.

**Comment by az0** [comment] 2020-03-08 20:16
On the default Ubuntu 16.04 theme, the icons look OK. Here's a screenshot
![Ubuntu 1604 icon](https://user-images.githubusercontent.com/933680/76170403-45cf3080-6147-11ea-990b-4d47a78909ea.png)

So far this looks like the icon theme ubuntu-mono-dark is missing an icon

**Comment by mkhon** [comment] 2020-04-04 16:47
The same issue in Ubuntu 18.04 (ubuntu-mono-dark is the default icon theme).

**Comment by rados** [comment] 2020-12-18 17:48
@az0 
Hey guys I can trace this further. 

@saiballo @ediowar @mkhon
For now could you try latest version of the application and check if the problem persists?

Looks like ubuntu-mono-dark displays the clean icon on my machine (attached).

![image](https://user-images.githubusercontent.com/332322/102644701-ee480180-4169-11eb-8941-27c803da88fb.png)

**Comment by saiballo** [comment] 2020-12-18 18:08
now i can see the icon! version 3.9.0



![aaaa](https://user-images.githubusercontent.com/3473910/102646466-5eec1f80-4164-11eb-8561-eafde964e884.png)

**Comment by rados** [comment] 2021-03-27 23:18
@ediowar @mkhon 
You can verify if this has been fixed.

**Comment by az0** [comment] 2021-05-18 04:48
I am closing because the original reporter (saiballo) confirmed that it works (December 18, 2020 with version 3.9.0.) It also works for me now with Ubuntu 20.10 with the yaru and ubuntu-mono-dark icon themes.

No word recently from ediowar and mkhon, but saiballo, thank you for confirming.

**Closed by az0** 2021-05-18 04:48 UTC
Labels: gui, priority:high
