### ISSUE TITLE
BleachBit "crash" at shutdown with problem S&D Update

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#424] opened 2018-12-20 00:53 UTC
BleachBit "crash" (creates a error log) at shutdown of BB with error S&D Update. See attached log.

[BleachBit.exe.log](https://github.com/bleachbit/bleachbit/files/2697018/BleachBit.exe.log)

**Comment by az0** [comment] 2018-12-20 04:15
This looks like a duplicate of https://github.com/bleachbit/bleachbit/issues/308 . If you see this in one of the latest builds from https://ci.bleachbit.org/ , please reopen this ticket.

Also, I believe you are using a different Winapp2.ini file than what is provided automatically through BleachBit. The automated file will continue to remove the S&D entry until BleachBit 2.2 is released.

**Closed by az0** 2018-12-20 04:15 UTC
Labels: duplicate

**Comment by Tobias-B-Besemer** [comment] 2018-12-20 22:33
No, it's the standard WinApp2.ini file.

**Comment by Tobias-B-Besemer** [comment] 2018-12-20 23:10
Now the log have changed, but it still crash.

Btw.: I don't have the rights to reopen this bug.

[BleachBit.exe.2.log](https://github.com/bleachbit/bleachbit/files/2700882/BleachBit.exe.2.log)

**Comment by Tobias-B-Besemer** [comment] 2018-12-20 23:21
The new version crashed only ones - I'm now no more able to reproduce the crash!

**Comment by az0** [comment] 2018-12-24 17:10
I hear you are no longer able to reproduce the crash, so I will leave this closed. Thanks for checking
