### ISSUE TITLE
SQLite Python Traceback - DatabaseError: UNIQUE constraint failed

### ISSUE THREAD

**Issue by brahmastra2016** [bleachbit/bleachbit#120] opened 2016-02-16 00:40 UTC
Please can anybody help me understand/fix SQLite traceback error.
###### 

   Issue:
###### 

Error in execution of <bleachbit.Command.Function instance at 0x106c7bcb0>
Traceback (most recent call last):
  File "/Users/user/bleachbit/bleachbit/Worker.py", line 84, in execute
    for ret in cmd.execute(self.really_delete):
  File "/Users/user/bleachbit/bleachbit/Command.py", line 146, in execute
    self.func(self.path)
  File "/Users/user/bleachbit/bleachbit/Special.py", line 280, in delete_mozilla_url_history
    FileUtilities.execute_sqlite3(path, cmds)
  File "/Users/user/bleachbit/bleachbit/FileUtilities.py", line 307, in execute_sqlite3
    '%s: %s' % (Common.decode_str(exc), path))
DatabaseError: UNIQUE constraint failed: moz_places.url: /Users/user/Library/Application Support/Firefox/Profiles/lawxndmw.default/places.sqlite
###### 

System Info:
###### 

platform.mac_ver() = ('10.10.5', ('', '', ''), 'x86_64')
platform.platform = Darwin-14.5.0-x86_64-i386-64bit
platform.version = Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64
sys.argv = ['bleachbit.py', '--sysinfo']
sys.executable = /usr/local/opt/python/bin/python2.7
sys.version = 2.7.11 (default, Jan 22 2016, 08:28:37)

**Comment by az0** [comment] 2016-02-16 04:04
This looks like an error I have heard reported once on either Windows or Linux, but I have not reproduced it.

The SQL code that cleans history from Firefox/Mozilla places.sqlite is slightly complicated. One option is you could privately email me your places.sqlite file, and I could try to troubleshoot it here.

**Comment by az0** [comment] 2016-02-16 04:12
If you prefer to work on this yourself, look at the function delete_mozilla_url_history, and try to isolate the error to a specific SQL command

**Comment by brahmastra2016** [comment] 2016-02-16 12:20
thank for reply :) , let me spend sometime working on it and will let you know if hit stone wall.

it is exactly same as below bug on Linux and same workaround works too.

https://bugs.launchpad.net/bleachbit/+bug/1464299

Workaround :
Disable "Overwrite files to hide contents".

**Comment by brahmastra2016** [comment] 2016-02-17 01:15
This is what i am observing based on some debug, query with randomblob work but the next query with zeroblob fails.

Need somebody with SQL experience and expertise to guide as how to fix it Or explain as why we see this behavior.

SQL Query with randomblob works :)
#1
update moz_places set url = randomblob(length(url)),rev_host = randomblob(length(rev_host)),title = randomblob(length(title)) where id in (select moz_places.id from moz_places left join moz_bookmarks on moz_bookmarks.fk = moz_places.id where moz_bookmarks.id is null)

But the next command with zeroblob fails.
#2
update moz_places set url = zeroblob(length(url)),rev_host = zeroblob(length(rev_host)),title = zeroblob(length(title)) where id in (select moz_places.id from moz_places left join moz_bookmarks on moz_bookmarks.fk = moz_places.id where moz_bookmarks.id is null)

**Comment by az0** [comment] 2016-02-17 04:19
Zeroblob sets the existing data to zeros, and it makes sense that this could violate a constraint that the values are unique. In Special.py on line 47 try changing `update %s` to `update or ignore %s`. Does it help?

**Comment by brahmastra2016** [comment] 2016-02-17 18:56
i tried  to make below change under shred function for zeroblob i added "if col !="url" but then i get same contrain error for "update moz_hosts set host = zeroblob(length(host)) "

any suggestion ?

New Command - without URL:

update moz_places set rev_host = randomblob(length(rev_host)),title = randomblob(length(title)) where id in (select moz_places.id from moz_places left join moz_bookmarks on moz_bookmarks.fk = moz_places.id where moz_bookmarks.id is null)

#######
Change :
#######

def __shred_sqlite_char_columns(table, cols=None, where=""):
    """Create an SQL command to shred character columns"""
    cmd = ""
    if cols and options.get('shred'):
        cmd += "update %s set %s %s;" % \
                (table, ",".join(["%s = zeroblob(length(%s))" % (col, col)
                for col in cols if col != "url"]), where)     <<<<<<< IF Condition added

**Comment by az0** [comment] 2017-10-25 23:27
I think this was fixed by c43077dcf55d79f20706da66d1aaacd6e800ee87

If you see this with later code, please reopen

**Closed by az0** 2017-10-25 23:27 UTC
