### ISSUE TITLE
Unlocalized and lengthy text when requesting to run as admin

### ISSUE THREAD

**Issue by Elaborendum** [bleachbit/bleachbit#1109] opened 2021-02-03 05:10 UTC
**Describe the bug**
When launching Bleachbit, it requests to run as admin and during this it presents itself as "BleachBit frees space and maintains privacy by quickly wiping files you don’t need and didn’t know you had. Supported applications include Firefox, Flash, Internet Explorer, Java, Opera, Safari, GNOME, and many others." regardless of system language. Launchpad says that it is fully localized with my chosen language, spanish.

Is everything past "Bleachbit" intended? I haven't used it in a while so I can't really remember if its always been like this.

**To Reproduce**
1. Change system language
2. Launch Bleachbit
3. See error

**Expected behavior**
If intended, it would be displayed in spanish.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - BleachBit version 4.2.0

**Comment by abitrolly** [comment] 2022-11-06 16:40
The message comes from this line and it is used by `py2exe`.

https://github.com/bleachbit/bleachbit/blob/c32a76ad308f4c75a43c41cf75b3f4e78ed53883/setup.py#L50

 Looks like `py2exe` bug. Can you add screenshot for a reference?

**Comment by abitrolly** [comment] 2022-11-06 18:46
As I don't have Windows for like 5 years, it is hard for me to debug where this message comes from. I can only recommend change each line in https://github.com/bleachbit/bleachbit/blob/master/setup.py where `APP_DESCRIPTION` is used, like adding a prefix, and rebuild the installer.

**Comment by abitrolly** [comment] 2022-11-06 18:49
Actually we can try using AppVeyor for that. I see that it produces installer for PR. Like this https://ci.appveyor.com/project/az0/bleachbit/build/artifacts are binaries for https://github.com/bleachbit/bleachbit/pull/1398

Let me try it.

**Comment by abitrolly** [comment] 2022-11-06 19:23
@Elaborendum can you try this build - https://ci.appveyor.com/project/az0/bleachbit/builds/45293024/artifacts - and post the screens here?

Maybe this could help with screenshooting https://stackoverflow.com/questions/4046940/how-to-screen-shot-a-uac-prompt

**Comment by az0** [comment] 2022-12-29 17:32
@Elaborendum 

Are you able to test please? (See last comment.)

**Comment by az0** [comment] 2022-12-29 17:33
The updated builds for troubleshooting this issue are here: https://github.com/bleachbit/bleachbit/pull/1419#issue-1437504886

>[BleachBit-4.4.2.2275-portable.zip](https://github.com/bleachbit/bleachbit/files/9946711/BleachBit-4.4.2.2275-portable.zip)
[BleachBit-4.4.2.2275-setup.exe.zip](https://github.com/bleachbit/bleachbit/files/9946763/BleachBit-4.4.2.2275-setup.exe.zip)
[BleachBit-4.4.2.2275-setup-English.exe.zip](https://github.com/bleachbit/bleachbit/files/9946764/BleachBit-4.4.2.2275-setup-English.exe.zip)

**Comment by mcl21014** [comment] 2023-01-01 20:39
Using the test build, the UAC prompt just says "bleachbit.exe" and no wordy description. However, all my 2 Windows machines are on Windows 11, and the WinDevEval image for Virtualbox is based off 11 22H1. So I cannot say for sure if the issue is fixed as I don't have access to Windows 10 anymore.

**Comment by sanjaykaria** [comment] 2023-01-05 11:56
@az0  
I get this when starting bleachbit.exe on Windows 10 20H2 with BleachBit-4.4.2.2275.

![image](https://user-images.githubusercontent.com/3830310/210774695-47e86c62-1bf4-4ef8-8f9d-8b943a61eb88.png)

**Comment by az0** [comment] 2023-01-07 17:12
@sanjaykaria 
It is normal for the application to request administrator privileges, so it can clean the whole system. It is also okay to decline, but some functionality will be missing.

**Comment by az0** [comment] 2023-01-07 17:27
@sanjaykaria 

Maybe you meant that it was fixed because the long text was not shown there. I agree, so I am closing. More details at https://github.com/bleachbit/bleachbit/issues/1134#issuecomment-1374545142

**Closed by az0** 2023-01-07 17:27 UTC
Labels: new, platform: windows

**Comment by sanjaykaria** [comment] 2023-01-08 05:05
@az0 

Yes that's right, I meant to say that the long description is not coming in the build I tested.

**Comment by az0** [comment] 2023-02-04 22:07
I am splitting apart milestones 4.6 and 5.0 where 4.6 still has Python 3.4 and 5.0 has Python 3.10, which is not ready yet, and this issue goes with 5.0.

**Comment by az0** [comment] 2024-04-20 20:38
Two options to try for anyone having this issue

[Build 2584](https://ci.bleachbit.org/?prefix=dl/4.6.1.2584-processname/). This is the latest version of BleachBit (4.6.x) using the old framework (Python 3.4, GTK 3.24).

[Build 2467](https://ci.bleachbit.org/?prefix=dl/4.4.2.2467-mkhon-python310/) uses the new framework (Python 3.10.7), but it has an old build date July 2023. This build has known issues, so it's just for testing, so I recommend portable (zip) over installer (exe).  Once ready, this will be BleachBit 5.0.

Each build may have an improved process name in a different way.

Google Chrome may show safety warnings for the site ci.bleachbit.org . This is a false positive, but they won't give me details on the issue.

For cross referencing, here are related issues:  https://github.com/bleachbit/bleachbit/issues/617 https://github.com/bleachbit/bleachbit/issues/1000 https://github.com/bleachbit/bleachbit/issues/1109 https://github.com/bleachbit/bleachbit/issues/1134 https://github.com/bleachbit/bleachbit/issues/1655

**Comment by az0** [comment] 2024-08-26 04:19
**Please test [BleachBit 4.6.1 beta ](https://www.bleachbit.org/news/bleachbit-461-beta) has a fix for a shorter process name. If you still see an issue with the process name, reopen this issue.**

While testing that, please also check that there are no issues with the digital certificate. When running the installer and running the application, you may see a User Account Control pop-up with my name _Andrew Ziem, Open Source Developer_. You may see _Verified Publisher_, but you should not see _Publisher Unknown_. If you see an issue with the digital certificate, please open a new issue ticket.
