### ISSUE TITLE
Bleachbit install issues a syntax warning in python script.

### ISSUE THREAD

**Issue by ChooChooAl** [bleachbit/bleachbit#1094] opened 2021-01-17 14:25 UTC
Setting up bleachbit (3.9.0-1) ...
/usr/share/bleachbit/bleachbit/__init__.py:260: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if msgctxt is not None and msgctxt is not "":

Running command line install on Linux Mint Cinnamon 20.1 64bit.

**Comment by abitrolly** [comment] 2021-01-17 19:59
Duplicate of #902 fixed by e5cc3263ad8038d1e274f67ba5071b027c59cca2.

Which version of BleachBit do you use?

**Comment by ChooChooAl** [comment] 2021-01-17 21:00
It's in the comment,  bleachbit (3.9.0-1),  it's the latest version Mint cinnamon is giving out.  
Seems the same info shown in #902.    
It seems to work even with this hick-up on the install.

**Comment by abitrolly** [comment] 2021-01-18 02:11
Missed that. Well, use a newer version from https://www.bleachbit.org/download

**Comment by az0** [comment] 2021-01-18 03:44
Ubuntu, Linux Mint, and other distributions often have outdated versions of BleachBit in their repositories, so please keep up to date using the link @abitrolly posted. (Thanks)

**Closed by az0** 2021-01-18 03:44 UTC
