### ISSUE TITLE
Error In BleachBit

### ISSUE THREAD

**Issue by swap-linux9431** [bleachbit/bleachbit#1020] opened 2020-09-24 12:33 UTC
Sir/Ma'am,

Bleachbit on Ubuntu 20.04 LTS is continuously showing the following error. I've tried a lot but i cant see any solution to it, I even uninstalled it and reinstalled but no solutions so far. So please help me with my issue is as following:

**Error when checking for updates: 
Traceback (most recent call last):
  File "/usr/share/bleachbit/bleachbit/GUI.py", line 1160, in check_online_updates
    updates = Update.check_updates(options.get('check_beta'),
  File "/usr/share/bleachbit/bleachbit/Update.py", line 155, in check_updates
    opener.addheaders = [('User-Agent', user_agent())]
  File "/usr/share/bleachbit/bleachbit/Update.py", line 87, in user_agent
    dist = platform.dist()
AttributeError: module 'platform' has no attribute 'dist'**

**Comment by az0** [comment] 2020-09-26 19:23
This is a duplicate of https://github.com/bleachbit/bleachbit/issues/819

You are using an old version of BleachBit. Because of Ubuntu's "no rolling release policy," its repository often has an old version. Ubuntu LTS users might even have an ancient version of BleachBit. Generally I recommend getting a new version from https://www.bleachbit.org/download . Right now I recommend https://www.bleachbit.org/news/bleachbit-410-beta

**Closed by az0** 2020-09-26 19:23 UTC
