### ISSUE TITLE
Path Error 4.6

### ISSUE THREAD

**Issue by EGorlomi** [bleachbit/bleachbit#1574] opened 2023-11-05 23:22 UTC
[WinError 3] The system cannot find the path specified: '\\\\?\\C:\\WINDOWS\\Sysnative\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5': Command to delete C:\WINDOWS\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5

**Comment by az0** [comment] 2023-11-06 05:19
Are you on Windows 10 or 11?

Try [BleachBit version 4.6.0](https://www.bleachbit.org/news/bleachbit-460). Does this help?

**Comment by justa-rowdy** [comment] 2023-11-10 00:27
Windows 10 Pro 64 bit
Version 22H2
BleachBit version 4.6.0
Build number 253

Since installing Bleachbit Version 4.6.0 on 11/5/2023, I can confirm that I am receiving this exact same error message every time I run BleachBit.  After some research on where to find and how to access, I was able to find Content.IE5 in the following directory.  C:\Windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5

Additionally, Sysnative in the error message C:\WINDOWS\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5, is supposedly a Windows virtual folder that doesn't actually exist.  Also, in 64-bit Windows systems should automatically point to the System32 folder.  

That is, if I actually understood what I read in my research since I am not a developer.

**Comment by rados** [comment] 2023-12-06 20:23
@az0 I can trace this one.

**Comment by az0** [comment] 2023-12-06 23:11
Ok. At a quick glance, I would check if there was a change related to WoW redirection.

**Comment by rados** [comment] 2023-12-09 13:13
@EGorlomi, @justa-rowdy, what were the steps to reproduce it?

**Comment by rados** [comment] 2023-12-09 18:46
Just tried (Windows 10, Bleachbit 4.6.0) to clean IE cache with admin and non admin users - in both cases it shows that the folder in question is handled properly.

Delete 0B C:\Windows\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5

**Comment by justa-rowdy** [comment] 2023-12-09 20:11
Windows 10 Pro 64 bit, Version 22H2
BleachBit version 4.6.0, Build number 2537

I don't do anything special to get the error to show up.  The following error shows up every time I run BleachBit.

[WinError 3] The system cannot find the path specified: '\\\\?\\C:\\WINDOWS\\Sysnative\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5': Command to delete C:\WINDOWS\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5

**Comment by rados** [comment] 2023-12-09 20:54
Okay, thank you. What is your selection to clean? A screen shot will be enough.

**Comment by rados** [comment] 2023-12-10 12:05
Also a possible reason could be if the folder resides on a network drive.

**Comment by justa-rowdy** [comment] 2023-12-10 19:40
![tempsnip](https://github.com/bleachbit/bleachbit/assets/113783621/a05e5440-c266-4566-833b-486c5bc72bd5)
In the tempsnip.png, these are the places where the Content.IE5 files show up. So, not on a network drive,.  I'm assuming the important one to be cleaned is the one at C:\Windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5.  I have no idea what the other ones are or why they are in those locations.

**Comment by rados** [comment] 2023-12-10 19:48
And you just select the Cache of Internet Explorer like bellow picture? Another option is just to remove Bleachbit entirely and install the new (4.6.0) version after this - sometimes this helps.

<img width="274" alt="image" src="https://github.com/bleachbit/bleachbit/assets/332322/2b5fd87e-41ab-439d-8f82-a02b0b7cfbad">

**Comment by justa-rowdy** [comment] 2023-12-10 20:03
![tempsnip2](https://github.com/bleachbit/bleachbit/assets/113783621/8f0dd88c-e1f3-43d1-b35f-e44fba2d2521)
These are the selections that I have been using constantly for at least a year.

**Comment by justa-rowdy** [comment] 2023-12-11 17:55
Previous comment should read "consistently" not constantly.
I was trying to avoid this, but since I now have a record of my settings, I deselected all by the following and ran bleachbit with the indicated results.
![tempsnip3](https://github.com/bleachbit/bleachbit/assets/113783621/9f7a1d6b-95ae-4722-95ad-71febcbc75ba)

**Comment by justa-rowdy** [comment] 2023-12-11 19:42
Ran it again with the debugging turned on. Maybe this will narrow it down.
![tempsnip](https://github.com/bleachbit/bleachbit/assets/113783621/452e48dc-2363-49f0-aff6-d731c44a7b69)

**Comment by rados** [comment] 2023-12-14 00:53
@justa-rowdy, Interesting and thank you for this comprehensive report. Seems like there is a process in action which keeps the file open and Bleachbit cannot take over. So, what about after fresh reset of the system and no other programs running?

**Comment by throwromans** [comment] 2023-12-16 07:59
> @justa-rowdy, Interesting and thank you for this comprehensive report. Seems like there is a process in action which keeps the file open and Bleachbit cannot take over. So, what about after fresh reset of the system and no other programs running (no anti-virus, etc.)?
> 
> Edit: If you have access to another machine with same OS you can try and see what will happen and compare the surroundings. I've tried to reproduce this on several Win 10 machines with no success...

also facing this same issue so this is not something limited to this other user

**Comment by rados** [comment] 2023-12-16 11:02
@throwromans, thank you, this is really valuable information. What steps would you recommend to reproduce this issue?

**Comment by rados** [comment] 2023-12-16 15:56
ChatGPT:

"If this folder is being locked or used for an unusually long time, it could indicate a running process that's heavily reliant on Internet Explorer's caching system. If this leads to issues, investigating current running processes, scheduled tasks, or reviewing which applications are actively using Internet Explorer's components might provide further insights."

**Comment by rados** [comment] 2023-12-16 20:34
I think I've found something. In version 4.4.2 this folder is not cleaned at all because the folder path in the cleaner xml is not correct. Then, four months ago we introduced a fix. And since the fix the folder is cleaned - this is confirmed by a reporter of the bug (that the folder is not cleaned at all). You can follow this short conversation here:

https://github.com/bleachbit/bleachbit/issues/1514

So, still my best suggestion is that in some cases this folder is being held by another process which prevents Bleachbit to clean it.

**Comment by justa-rowdy** [comment] 2023-12-18 17:28
I have tried several methods to find a process that might be keeping Content.IE5 in-use.  Including both Resource Monitor and Process Explorer. I cannot find anything that proves the file is in-use.
![Capture6](https://github.com/bleachbit/bleachbit/assets/113783621/d8e61500-cf4e-4272-a754-40b8e0c42f42)

**Comment by justa-rowdy** [comment] 2023-12-18 20:36
Downloaded BleachBit V4.4.2 (portable version) and ran it with out any errors.  V4.4.2 appeared to clean the Content.IE5  without any error messages. Therefore, it appears that it was not in-use.  Then ran V4.6.0 and the error reappears. The following shows the results of V4.4.2.
![Capture7](https://github.com/bleachbit/bleachbit/assets/113783621/65d71f85-998b-483e-994a-d486153d5fca)

**Comment by rados** [comment] 2023-12-18 22:19
In 4.4.2 we deal with Content.IE5 that is in a user folder, not in the system folder (C:\Windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache).

**Comment by rados** [comment] 2023-12-22 16:32
@justa-rowdy, great thanks for the support. Indeed, the idea about another process holding the path seems not relevant. It will be good to check if your sysnative redirection works. For example you can execute the following commands:

Click Start.
Type %windir%\SysWoW64\cmd.exe in Start Search box.
echo %programfiles% -> should display 'C:\Program Files (x86)'
cd C:\Windows\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5 -> should enter the folder 

Please share your results. :)

**Comment by justa-rowdy** [comment] 2023-12-22 19:09
Ran the commands in Terminal.  Initially, I was unable to get to Content,IE5.  It appears a permissions issue at the config directory is preventing from going any further. 

When running Terminal with Administrator privileges I was able to get to Content.IE5.
![Capture10](https://github.com/bleachbit/bleachbit/assets/113783621/ce340944-0b52-4aa0-bb9b-54b20ce279ec)

The account I'm using is an Administrator account.

**Comment by rados** [comment] 2023-12-22 22:14
@justa-rowdy, may try to you delete the folder from WoW64 cmd in both cases (admin and non-admin). You can re-create it between the two calls:

rmdir C:\Windows\System32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5

**Comment by Surfride10** [comment] 2023-12-25 23:11
With the introduction of 64bit in Windows 7, Microsoft moved the 64bit dlls into system32 and the 32bit dlls to syswow64.   I know makes your head explode; 32 has the 64 and 64 has the 32, yet MS did this to preserve the dll search path.  Sysnative is a 32bit virtual folder to facilitate 32bit processes calling 64bit dlls..  sysnative is restricted to 32bit processes by the OS making it invisible to 64bit processes like explorer and powershell.  As bleachbit is a 32 bit process, my theory is the path C:\WINDOWS\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5 inadvertently appended sysnative when it should be system32.  also, .\INETCahche\Content.IE5 is a reparse point and links to .\INetCache\IE

**Comment by rados** [comment] 2023-12-26 00:55
@Surfride10 Thank you. We are trying to determine why in some cases it works and in some it does not.

@justa-rowdy Have you tried to remove Bleachbit entirely and install version 4.6 afterwords? Sometimes this helps.

**Comment by Surfride10** [comment] 2023-12-26 02:07
after my post, i found an x86 version of powershell -and- as documented
\windows\sysnative is valid and available.  could this be a clue, building
on your theory of a re-install, i loaded up processexplorer to see if x64
libraries are loading with bleachbit.exe, and I have a few, which could
possibly kill the path
C:\WINDOWS\sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache
if an x64 dll is part of the call, i have not looked at your code...

bleachbit.exe on my system is loading x64 of ntdll.dll (kernel), wow64*.dll
(thunking)

one thing you could try is replacing sysnative with system32 in the path,
happy to test ...

thanks!

**Comment by rados** [comment] 2023-12-26 19:04
@Surfride10 Thank you. Do you experience the same error or it works at your side? If you read carefully the comments above, you will see that we are testing the sysnative resolution through a 32 bit cmd with: %windir%\SysWOW64\cmd.exe. Just made another test here on my Win 10 box and it worked again - Bleachbit 4.6.0  deleted the content of C:\WINDOWS\sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache.

**Comment by Surfride10** [comment] 2023-12-26 20:44
I am getting the error in the bb ui on my Server 2019 (win 10 1089)


*[WinError 3] The system cannot find the path specified:
'\\\\?\\C:\\WINDOWS\\Sysnative\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5':
Command to delete
C:\WINDOWS\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5*

I do not believe this is about sysnative its about the path
C:\WINDOWS\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5
translates to
C:\WINDOWS\SysWoW64\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5
this path does not exist, the wheels fall off at
C:\WINDOWS\SysWoW63\config\systemprofile\AppData\Local\Microsoft\Windows\
.\inetcache does not exist in the syswow64 path

the goal is deleting the contents of
C:\WINDOWS\system32\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5
regardess of .\system32\cmd.exe or .\syswow64\cmd.exe

hope this helps

**Comment by justa-rowdy** [comment] 2023-12-26 22:14
Uninstalling and reinstalled BleachBit 4.6 for Windows, did not correct the problem and I continued to get the reported error message.

Uninstalled a second time.  Then performed a search on "BleachBit" using Everything.  Found that there were remaining folders with files related to BleachBit that were not removed during the Uninstall. 

With the **exception** of C:\Users\Anonymous\AppData\Roaming\BleachBit **(cleaners folder and bleachbit.ini)**,  I then deleted those remaining items related to Bleachbit In the Local and Roaming directory paths.  Unfortunately, I did not document them or back them up.

Reinstalled Bleachbit 4.6.  Ran with no errors.  Also, installed BleachBit Portable 4.6 and ran it with no errors.

So, it appears that my issue regarding this error message has finally been resolved.  Also appears that something in those remaining files after the uninstall was causing the error message.  

Recommend to the next person that tries this **"fix"** to document the additional deleted files/folders after the uninstall and list them here so this can be further investigated.  I'm assuming that the installation and perhaps the uninstall may have to be modified to remove the problem file(s) to alleviate this in the future.  If, it is the only issue found causing this error message for some users.

**Comment by rados** [comment] 2023-12-27 00:02
@Surfride10, @justa-rowdy Thank you. Who would like to try one line of Python code? So the error appears on this call:

os.rmdir('\\\\?\\C:\\Windows\\Sysnative\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5')

and chatGPT advices us to not use \\\\?\\ with Sysnative. So let's try this on your machines:

os.rmdir('C:\\Windows\\Sysnative\\config\\systemprofile\\AppData\\Local\\Microsoft\\Windows\\INetCache\\Content.IE5')

Don't forget to install Python3.4 32bit version and to 'import os'. :)

**Comment by justa-rowdy** [comment] 2023-12-28 23:56
First, be aware that I received help with running the Python command.  Here are the results.
![Script Test](https://github.com/bleachbit/bleachbit/assets/113783621/3de47a94-3268-49c7-9d8b-e73e01a686a7)
I can run BleachBit many times in a row after this with out getting the error message. However, when restarting Windows and running BleachBit, the error message returns.

**Comment by rados** [comment] 2023-12-29 08:22
@justa-rowdy Great work! I just created a pull request with a possible fix. You can take the build when ready and try it.

https://github.com/bleachbit/bleachbit/pull/1620

**Comment by rados** [comment] 2024-01-14 14:05
@EGorlomi @throwromans @Surfride10 Hey, would you like to try this build, it contains a possible fix:

https://ci.appveyor.com/project/az0/bleachbit/builds/48848066/artifacts

**Comment by justa-rowdy** [comment] 2024-02-08 15:07
I would like to test the fix, but I need some instruction on how to do it.  I went to the URL in the previous message. How do I download and run 4.6.1.2564 from there?  Have I waited too long and perhaps the artifact was deleted?

**Comment by rados** [comment] 2024-02-11 06:41
@justa-rowdy I re-opened the pull request and the artefacts were recreated. You can find the build here:

https://ci.appveyor.com/project/az0/bleachbit/builds/49160391/artifacts

**Comment by justa-rowdy** [comment] 2024-02-16 13:55
This comment only applies to the Portable Version of 4.6.1.2564. **I still need to test the installed version.**

BleachBit version 4.6.1	Build number 2569 - Portable Version     Windows 10 Pro    Version 22H2  

In order to display Content.IE5 file paths, used Everything App running in Admin mode.  Searched on Content.IE5 folder, these three folders appear.  **Note:** All three of these folders do not always appear, it depends on whether they were previously deleted and/or whether they were recreated prior to running BleachBit the first, or subsequent times. 

![1](https://github.com/bleachbit/bleachbit/assets/113783621/adcf8a3d-69c0-48f4-a9b2-cc72f2049768)

Again, these three Content.IE5 folders do not always appear after Running BleachBit.  I believe it is because sometimes they are deleted and other times they are recreated.  It also depends on what apps are opened while or after running BleachBit, or if a restart/shutdown was performed prior to running BleachBit a second time.

Ran the **Portable BleachBit version 4.6.1, Build number 2569**, with only all of the Internet Explorer boxes checked.

![2](https://github.com/bleachbit/bleachbit/assets/113783621/df91bbce-091f-4562-8790-cc3790c78171)

**Portable Version appears to consistently delete Content.IE5 from 

C:\Users\?????????????\AppData\Local\Microsoft\Windows\INetCache
and
C:\WINDOWS\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5

The C:\Windows\ServiceProfiles\LocalService\AppData\Local\Microsoft\Windows\INetCache\Content.IE5 remains. It is unknown if this remaining Content.IE5 folder should have been deleted or not?**

![3](https://github.com/bleachbit/bleachbit/assets/113783621/912d9f9d-de20-4fd3-89a0-0000eb63fa2d)

![4](https://github.com/bleachbit/bleachbit/assets/113783621/55c75bb2-ad87-4b87-8f01-ebc40b853558)

**Immediately running the portable version of BleachBit a 2nd, 3rd, 4th time does not produce any errors.**  Assuming no errors are produced because the two folders were already deleted.

**Comment by justa-rowdy** [comment] 2024-02-19 00:03
Using the same settings as the Portable version described previously, the Full Version 4.6.1.2564 appears to consistently delete Content.IE5 from

C:\Users?????????????\AppData\Local\Microsoft\Windows\INetCache
and
C:\WINDOWS\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5 

**However, I was also able to get the error message to return and failure to delete Content.IE5 from C:\WINDOWS\Sysnative\config\systemprofile\AppData\Local\Microsoft\Windows\INetCache\Content.IE5 when I used the previous Bleachfit.ini and winapp2.ini files that remained after uninstall and install of Version 4.6.1.2564.** 

Was finally able to completely remedy by deleting both the old Bleachbit.ini and Winapp2.ini that remained after the uninstall.  Restarted PC. Then, used the new Bleachbit.ini created during install, and then checked the preference box to download the Winapp2.ini from the community.  Prior to running BleachBit, I closed and reopened BleachBit so that the additional cleaners from Winapp2.ini were visible.

Still no Content.IE5 error message after selecting all the cleaner options.

**Comment by az0** [comment] 2024-03-03 22:01
> Was finally able to completely remedy by deleting both the old Bleachbit.ini and Winapp2.ini that remained after the uninstall. Restarted PC. Then, used the new Bleachbit.ini created during install, and then checked the preference box to download the Winapp2.ini from the community. Prior to running BleachBit, I closed and reopened BleachBit so that the additional cleaners from Winapp2.ini were visible.

That's unexpected

>Still no Content.IE5 error message after selecting all the cleaner options.

Thank you for testing. I am hearing this is resolved, so I will close. Fix will be in the next release

**Closed by az0** 2024-03-03 22:01 UTC
Labels: bug, bug: regression, platform: windows
