### ISSUE TITLE
Gdk-CRITICAL **: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#922] opened 2020-05-15 12:16 UTC
openSUSE Tumbleweed 20200511 KDE
Desktop Sessions: Plasma, Plasma (Wayland), Plasma (Full Wayland), Openbox
Running from source code, Git revision https://github.com/bleachbit/bleachbit/commit/f93647aa02b8c9a985c6c6dc84026cf6a22a28ef
BleachBit version 4.0.1
GTK version 3.24.20
```
dzmitry@dhcppc0:~/Downloads/bleachbit-master> sudo python3 bleachbit.py
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(bleachbit.py:10332): Gdk-CRITICAL **: 17:00:29.248: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
Unable to init server: Could not connect: Connection refused

(bleachbit.py:10332): Gtk-WARNING **: 17:00:29.255: cannot open display: 
```
Same with https://download.opensuse.org/repositories/home:/andrew_z/openSUSE_Tumbleweed/noarch/bleachbit-4.0.0-1.11.noarch.rpm
```
dzmitry@dhcppc0:~> sudo zypper dup
Loading repository data...
Reading installed packages...
Warning: You are about to do a distribution upgrade with all enabled repositories. Make sure these repositories are compatible before you continue. See 'man zypper' for more information about this command.
Computing distribution upgrade...

Problem: problem with installed package bleachbit-4.0.0-1.11.noarch
 Solution 1: install bleachbit-4.0.0-1.1.noarch (with vendor change)
  obs://build.opensuse.org/home:andrew_z  -->  openSUSE
 Solution 2: keep obsolete bleachbit-4.0.0-1.11.noarch

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 2
Resolving dependencies...
Computing distribution upgrade...

The following item is locked and will not be changed by any action:
 Installed:
  bleachbit

Nothing to do.
```

**Comment by fkru** [comment] 2020-05-16 08:51
I confirm your observation with openSUSE TW20200514 and KDE. Seems to be a dup of #919?

**Comment by topas-rec** [comment] 2020-06-22 19:17
Have this on Debian Buster (10.4) using Wayland and Gnome.
Do **NOT** have this when I switch to Gnome on Xorg.

**Comment by abitrolly** [comment] 2020-11-07 18:14
@ediowar can you paste the output of `sudo python3 bleachbit.py --sysinfo` here for your openSUSE? I guess you get the same error when running `gedit`, `meld` or any other GTK app with `sudo`, is that right?

I see that BleachBit is quite popular on openSUSE forums. There are [hints to use `xdg-su`](https://forums.opensuse.org/showthread.php/405624-sudo-doesnt-open-X-programs) run desktop apps with `sudo` there. Would be nice to get confirmation that it helps.

There is also a thread about [new package](https://forums.opensuse.org/showthread.php/539180-Please-Release-quot-Bleachbit-quot-System-Cleaner-For-Tumbleweed?p=2927648#post2927648) which suggests that some fixes were landed in openSUSE packages including the `Gdk-CRITICAL` bug mentioned.

Let's see if the bug also repeated with newer official package.

**Comment by abitrolly** [comment] 2020-11-07 18:16
@topas-rec may I ask you to open a new issue with the output of `bleachbit --sysinfo` for Debian Buster and Wayland?

**Comment by ediowar** [comment] 2020-11-07 22:55
> @ediowar can you paste the output of `sudo python3 bleachbit.py --sysinfo` here for your openSUSE? I guess you get the same error when running `gedit`, `meld` or any other GTK app with `sudo`, is that right?

```
dzmitry@localhost:~/Downloads/bleachbit/bleachbit-master> sudo python3 bleachbit.py --sysinfo
[sudo] password for root: 
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(bleachbit.py:8032): Gdk-CRITICAL **: 01:46:23.967: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
BleachBit version 4.1.0
GTK version 3.24.22
SQLite version 3.33.0
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /root/.config/bleachbit
personal_cleaners_dir = /root/.config/bleachbit/cleaners
system_cleaners_dir = /home/dzmitry/Downloads/bleachbit/bleachbit-master/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = None
os.getenv('LOGNAME') = root
os.getenv('USER') = root
os.getenv('SUDO_UID') = 1000
os.path.expanduser('~') = /root
platform.linux_distribution() = ('', '', '')
platform.platform = Linux-5.9.1-1-default-x86_64-with-glibc2.2.5
platform.version = #1 SMP Mon Oct 26 07:02:23 UTC 2020 (435e92d)
sys.argv = ['bleachbit.py', '--sysinfo']
sys.executable = /usr/bin/python3
sys.version = 3.8.5 (default, Jul 20 2020, 17:41:41) [GCC]
__file__ = /home/dzmitry/Downloads/bleachbit/bleachbit-master/bleachbit/Diagnostic.py
```
```
dzmitry@localhost:~/Downloads> sudo gedit
Unable to init server: Could not connect: Connection refused

(gedit:28908): Gtk-WARNING **: 01:27:06.267: cannot open display: 
```
> I see that BleachBit is quite popular on openSUSE forums. There are hints to use xdg-su run desktop apps with sudo there. Would be nice to get confirmation that it helps

I confirm it helps.

**Comment by abitrolly** [comment] 2020-11-08 04:17
@ediowar thanks for the testing. I'd say the resolution of the problem is on the `openSUSE` side. It may be the policy that GUI tools should not be run with `sudo`, and those users who still want it, should be advanced enough to use `xdg-su`. The best way to confirm this is to ask at https://forums.opensuse.org/forumdisplay.php/669-Applications if packages like `BleahBit` and `gedit` deliberately do not support running GUI apps under `sudo`.

I guess `openSUSE` package needs setup with environment that is required by GTK when run with `sudo`. I can't say what is that environment - it may be different for X11 and for Wayland, but from the forum threads it looks like there are knowledgeable people who can help with that.

I'd keep this issues open until you can get the reply there.

**Comment by ediowar** [comment] 2020-11-10 18:20
There is no issue in the Terminal - Super User Mode. Can I close issue?

**Comment by abitrolly** [comment] 2020-11-10 18:46
@ediowar yes, please. `xdg-su` is the solution for other users coming from `openSUSE`.

**Comment by ediowar** [comment] 2020-11-10 19:04
Why only `xdg-su` if Terminal - Super User Mode is installed by default during openSUSE Tumbleweed installation?

**Comment by abitrolly** [comment] 2020-11-10 19:09
@ediowar I didn't know about that. Sound like a proper solution to me.

**Closed** 2020-11-10 19:12 UTC
Labels: bug, priority:high

**Comment by rei-vilo** [comment] 2021-07-25 14:08
Using `xhost +SI:localuser:root` before launching `sudo bleachbit` solved the issue on my case.

BleachBit version 4.4.0
Debian 4.19.181-1 (2021-03-19) 
Gnome 3.30.2
