### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 60: ordinal not in range(128)

### ISSUE THREAD

**Issue by Axeltherabbit** [bleachbit/bleachbit#361] opened 2018-07-21 22:46 UTC
full error:
Exception while running operation 'system': ''ascii' codec can't encode character u'\xf3' in position 60: ordinal not in range(128)'
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 338, in run_operations
    for dummy in self.clean_operation(operation):
  File "/usr/share/bleachbit/Worker.py", line 149, in clean_operation
    for cmd in backends[operation].get_commands(option_id):
  File "/usr/share/bleachbit/Cleaner.py", line 536, in get_commands
    for filename in children_in_directory(dirname, True):
  File "/usr/share/bleachbit/FileUtilities.py", line 168, in children_in_directory
    for (dirpath, dirnames, filenames) in os.walk(top, topdown=False):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 296, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib/python2.7/os.py", line 286, in walk
    if isdir(join(top, name)):
  File "/usr/lib/python2.7/genericpath.py", line 49, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 60: ordinal not in range(128)

**Comment by az0** [comment] 2018-07-22 15:02
Which version of BleachBit? Did you install it from this site or from your Linux distribution's repository? Which Linux distribution?

**Comment by Axeltherabbit** [comment] 2018-07-22 15:09
```
[ therabbit@xxx ] ~
$> bleachbit -v    
no default locale found.  Assuming 'C'

BleachBit version 2.0
Copyright (C) 2008-2018 Andrew Ziem.  All rights reserved.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
[ therabbit@xxx ] ~
$> uname -a
Linux xxx 4.17.5-1-ARCH #1 SMP PREEMPT Sun Jul 8 17:27:31 UTC 2018 x86_64 GNU/Linux
```

**Comment by az0** [comment] 2019-04-19 15:31
Sorry for the slow reply. :( I think this was fixed in [BleachBit version 2.2](https://www.bleachbit.org/news/bleachbit-22). Would you please test it and let me know?

**Comment by Tobias-B-Besemer** [comment] 2019-04-19 16:48
> Sorry for the slow reply. :( I think this was fixed in [BleachBit version 2.2](https://www.bleachbit.org/news/bleachbit-22). Would you please test it and let me know?

Then should the issue https://github.com/bleachbit/bleachbit/issues/430 be fixed, too?

**Comment by az0** [comment] 2019-04-19 20:47
They're both encoding errors, but they're unrelated parts of the BleachBit code.

**Comment by Tobias-B-Besemer** [comment] 2019-04-19 21:19
K!

**Comment by az0** [comment] 2019-04-21 09:24
This seems to be caused by the environment variable `LANG` set to `C`. As a workaround, try setting your language like `LANG=en_US.UTF-8 bleachbit`. I still plan to fix it to work with `LANG=C`

**Comment by az0** [comment] 2019-04-21 09:35
This looks related to Python bug https://bugs.python.org/issue13643 . 

@Axeltherabbit  What do you think about setting `LANG` to a Unicode locale instead of `C` as a solution instead of a workaround?

**Comment by Axeltherabbit** [comment] 2019-04-21 12:27
Hello,it was and old issue, I've not got it anymore :D, idk how and why btw my locale now is this:
```
locale
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=en_GB.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=en_GB.UTF-8
LC_MESSAGES=C
LC_PAPER=en_GB.UTF-8
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=en_GB.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

**Comment by az0** [comment] 2019-04-22 00:35
OK, setting LANG=C can cause issues. In this case BleachBit was traversing a directory tree, and there was a filename with Unicode encoding. This combination in Python causes issues. 

We now understand it, and it works for you, so I'll mark it as closed.

**Closed by az0** 2019-04-22 00:35 UTC
Labels: bounty, bug
