### ISSUE TITLE
https://ci.bleachbit.org/ is flagged as Dangerous by Google's Safe Browsing

### ISSUE THREAD

**Issue by tonyping** [bleachbit/bleachbit#1506] opened 2023-06-28 03:33 UTC
**Describe the bug**
The subdomain, [https://ci.bleachbit.org/](https://ci.bleachbit.org/), that contains unstable builds of Bleachbit on Windows, is flagged as "Dangerous" by Google's Safe Browsing. 

![Screenshot 2023-06-27 222536](https://github.com/bleachbit/bleachbit/assets/7454880/c11df5ec-731e-4725-8ba8-0d1ab9fcb704)

**To Reproduce**
1. Go to the Bleachbit download page: https://www.bleachbit.org/download
2. Click on: [Unstable builds for Windows](https://ci.bleachbit.org/)
3. A red, full-screen "dangerous" interstitial appears in Google Chrome w/ Safebrowsing enabled. 

![Screenshot 2023-06-27 222038](https://github.com/bleachbit/bleachbit/assets/7454880/c461aaad-aa04-4bd7-b8ea-faad7af61730)

4. Click on "Details", then "Proceed to page" to temporarily bypass warning and load the page.

![Screenshot 2023-06-27 225359](https://github.com/bleachbit/bleachbit/assets/7454880/6df7c130-2a3d-4a46-a279-7f90bd9fc3d5)

**Expected behavior**
No Safebrowsing flag.

**Screenshots**
In rest of post.

**Desktop (please complete the following information):**
 - OS: [Win 11]
 - Browser: Chrome 115, w/ the Safe Browsing setting turned On.
 - BleachBit version [N/A]

**Additional context**
Google's Transparency Report, located at https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fci.bleachbit.org%2F&hl=en-US, currently that shows the site is marked unsafe, due to containing malware.

![Screenshot 2023-06-27 222633](https://github.com/bleachbit/bleachbit/assets/7454880/4948d323-3b86-4a81-be35-090e9ccc198e)

So I did some research on how to report falsely flagged domains, and so far all I can find out from the webmaster page is that Google says if a page is flagged for "legal reasons, policy violations, or low-quality/spammy pages", only site owners can be the ones to file a review: https://support.google.com/webmasters/answer/6347750?hl=en#zippy=%2Crequest-a-review @az0 

But in this case, if a site is flagged for malware, it just says "Review [our definition of malware and unwanted software](https://support.google.com/webmasters/answer/3258249) and fix any issues that you see in your site." But it basically ends right there, and nothing said on how to file a review.

If anyone happens to know more details on this process, I'd be glad to know how it's done. Otherwise it looks like it's just up to @az0 to somehow file a review.

**Comment by rados** [comment] 2023-07-02 04:33
@tonyping, thank you for the report. @az0, I also see this.

**Comment by tonyping** [comment] 2023-07-05 06:57
> @tonyping 
> 
> Google likes to automate everything, and I don't a way to report a false positive or get more details, so what's left is a blind process of reverse engineering.
> 
> 

Yeah I reached a similar conclusion from the docs. They basically want you to just figure it out for yourself, although their criteria for malware does leaves too much room for interpretation and can lead to grey areas. 

Those same areas that a software scanner can't reliably judge, nonetheless are still being tasked with. However, given Google's scale, I don't blame them, as I can't see any other feasible solution.

Have you tried Hybrid Analysis? https://www.hybrid-analysis.com

Maybe the sandbox reports show something. I submitted one but they do take a while to process.

**Comment by tonyping** [comment] 2023-07-06 00:42
Latest nightly: 

https://www.hybrid-analysis.com/sample/f8617873259294fe3392a44207e8df0a9996c5cb169f868d97e0e11c04ca997a/64a510f4b3c160a68707138a

**Comment by az0** [comment] 2023-07-06 02:52
Here's irony: Google flags the latest comment in this discussion as unsafe too.
![Screenshot_20230705_203632_Gmail](https://github.com/bleachbit/bleachbit/assets/933680/07b4e9ec-ce17-4b16-b5d5-9a77164f9712)

Security scanners flag BleachBit because 

1. The application contains the Python runtime and GTK toolkit, which are general and contain many capabilities.
2. By design, the application has to do "unsafe" things such as reading/changing the registry, marking files for deletion, and checking running processes.

In the past with the [false positives ](https://github.com/bleachbit/bleachbit/issues?q=is%3Aissue+label%3A%22false+positive%22+is%3Aclosed), the general process is to submit the application for review ("whitelisting"), even though they deal with many users and flagged software, but Google doesn't allow that. 

Adding my digital certificate many help, but that's for beta and final releases---not for the CI site.

**Comment by az0** [comment] 2023-07-15 21:40
Google Search Console identified that https://ci.bleachbit.org/?prefix=dl/4.4.2.2265-mkhon-python310/ was the problem. As I removed it earlier, I requested a re-review. For now, the whole site is still flagged

**Comment by az0** [comment] 2023-09-01 03:44
build 4.4.2.2467-mkhon-python310 has been up since July 29 without complaint from Google

**Comment by az0** [comment] 2023-09-10 18:25
Still no issues, so closing

**Closed by az0** 2023-09-10 18:25 UTC
Labels: false positive
