### ISSUE TITLE
Error message "There is no disk in the drive"

### ISSUE THREAD

**Issue by sionstar** [bleachbit/bleachbit#651] opened 2019-10-26 21:47 UTC
After updating to v 3.0 i get the error messages that there are no disc in drive D. I did download the installer, not the portable. uninstallation and reinstallation do not resolve the issue. However if i close the 2 error popup boxes, bleachbit starts up.

**Comment by az0** [comment] 2019-10-26 22:54
Are you on Windows 7?

**Comment by sionstar** [comment] 2019-10-26 23:15
Windows 8.1.
(Had the previous version running on the same computer without issues)

**Comment by az0** [comment] 2019-10-27 02:34
Does it look like this?  It might help me if you could please upload screenshots of the two error popup boxes.

![image001](https://user-images.githubusercontent.com/933680/67628685-67321e80-f82f-11e9-9e87-62423b9139f3.png)

Does Windows show the User Access Control dialog? (This is the popup with "Do you want to allow the following program...") For troubleshooting purposes, it would be interesting to try the opposite answer, either YES or NO, compared to what you normally do.

**Comment by sionstar** [comment] 2019-10-27 09:20
That is exactly how it looks. I do get 2 of those very same error popup messages.
The first 3-4 attempts to re install did not work. "error opening file for writing" popup. 
After i while i could install though.

Tried to download the portable version in case the installer and portable was mixed up, but it does not seem to be the problem. If i choose No to "Do you want to allow the following program.." It do not change anything. The both error pop up boxes still shows up. (Exactly like your screenshot)

**Comment by Tobias-B-Besemer** [comment] 2019-10-28 23:59
Do you have installed the last version maybe from drive D? Maybe from a USB Stick?
Uninstall and delete all registry entries related to BB and then reinstall may solve the issue...

**Comment by Tobias-B-Besemer** [comment] 2019-10-29 00:07
Just to better analyze the issue, you can try a new installer I written for BB.
Open this link, scroll to the bottom, open the Google Drive link and download the BB UMUI installer:
https://github.com/bleachbit/bleachbit/pull/527
After that uninstall BB and reinstall with the alternative installer. Does the error messages appear there, too ???
The alternative installer doesn't install the latest version of BB, but handles the registry entries much better...
...after have a look if error msgs appear, you can uninstall again.
Then you can try the normal installer again. All registry entries should now be deleted... Do you get by a new install the error msgs, again ???

**Comment by sionstar** [comment] 2019-10-29 12:55
Thank you for your advice,
I did run into the same problem with the 2 pop up error messages.
Bleachbit does work, but the both pop up errors must first be closed (I can use Continue or the X to proceed) I do however miss the options for cleaning Chrome that was once there, but now are gone.

I did never had any problem with the previous version of BleachBit.
Update was done upon opening the previous version and then got a message that update is available. Since then i have uninstalled BleachBit a couple of time, and download it back from the site. Downloads goes to C drive.

**Comment by az0** [comment] 2019-10-30 04:46
I did a little research, and the "no disk" error happened here with another project that uses GTK
https://github.com/Beep6581/RawTherapee/issues/3544 The claim was the build system had some drive (say Z:) that didn't exist on the end-user's machine.

I tested on a vanilla Windows 7 machine with  C: and D: drives. I'm attaching a screenshot. @sionstar  Which drives do you have?

![Windows7-My Computer](https://user-images.githubusercontent.com/933680/67829752-e75dbb80-fa9d-11e9-80e2-3101a6966e16.png)

**Comment by Tobias-B-Besemer** [comment] 2019-10-30 04:56
az0, what happens when you change the drive letter of the CD-Rom?

**Comment by sionstar** [comment] 2019-10-30 09:11
I have C: and D: 
C: - The default, while D: only contains Recovery Image.
(F: DVD No use.)

**Comment by az0** [comment] 2019-11-02 03:17
@sionstar 
Two more questions
First, do you know of any other applications you have ever used on this same computer that use GTK?  (GTK is the toolkit that BleachBit uses.) Examples include: GIMP, Inkscape, Pidgin, Transmission, Liferea, GnuCash, Abiword?

Second, would you please look for a file called `recently-used.xbel` in your user profile?  If you need help for how to search for it, let me know. It might be in the root directory of your user folder like `c:\users\(your username)`. If you can find it, please rename it or move it out the way, and try again.

**Comment by sionstar** [comment] 2019-11-03 01:19
@az0 
Thank you for your suggestions.
I did a search and found a XML document on GIMP. It is located here: C:\Users\MyUser\AppData\Local\BleachBit\share\cleaners                 
I cant recall that I have used GIMP for anything. Same with Pidgin: C:\Users\MyUser\AppData\Local
\BleachBit\share\cleaners
But no search results for: Inkscape, Transmission, Liferea, GnuCash, Abiword.

I did search my computer for recently-used.xbel, but did not find anything. (please correct me if I need search anywhere else)

**Comment by az0** [comment] 2019-11-03 03:10
@sionstar 

Thanks for checking, and thanks for your patience.

Could you please search for `recently-used.xbel` under the directory `%userprofile%\appdata\local\`? You can get there by typing that path into the top yellow region show in this screenshot. When I when there on my system, I saw BleachBit had made this file.

![recently-used](https://user-images.githubusercontent.com/933680/68079806-20a36d80-fdb5-11e9-9d07-9f0729321fb5.png)

**Comment by Tobias-B-Besemer** [comment] 2019-11-03 03:39
@sionstar, btw.: You found the cleaners of BB! The files belong to BB...

**Comment by sionstar** [comment] 2019-11-03 10:26
@az0
Thank you for your kind support.
I did navigate to the directory trying to find the recently-used-xbel but without result.

@Tobias-B-Besemer 
My apologizes. I was afraid that I was looking at the wrong place. Being a non-advanced user, somewhat struggling with english since its not my native language, I have a great risk failing even simpler tasks like this one. Though the screenshots are really helpful for me.

**Comment by Tobias-B-Besemer** [comment] 2019-11-03 15:50
@sionstar, no need to apologise!
You do a great job! :)
And thank you very much for reportkng the issue! :)
I just wanted to explain you that the files you found are normal and should be there where you found them.

**Comment by az0** [comment] 2019-11-03 17:56
@sionstar 

I haven't reproduced this on my system, but I think this is caused by a bug in GTK 3. I found a Windows error reporting option that should help. In about ten minutes when it finishes building, would you please test build [3.0.1.1346](https://ci.appveyor.com/project/az0/bleachbit/builds/28581214/artifacts)? If this helps, I'll merge the fix in for the next release.

**Comment by sionstar** [comment] 2019-11-03 21:40
@Tobias-B-Besemer
Thank you so much!

@az0
I tried the 3.0.1.1346 build and it works perfectly each time. I have no issues or warning display messages at all with this new build. Very appreciated!

**Comment by az0** [comment] 2019-11-03 21:41
@sionstar 
Thank you for confirming.

I am closing because @sionstar  and Mark (via email) both confirmed the fix.

**Closed** 2019-11-03 23:13 UTC
Labels: bug: encoding, bug:launch

**Comment by az0** [comment] 2020-01-23 04:24
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta). Perhaps you could test and write back here with any comments about how it addresses your issue.
