### ISSUE TITLE
Error: system.cache: Command to delete /root/.cache/wallpaper

### ISSUE THREAD

**Issue by OLavergne** [bleachbit/bleachbit#547] opened 2019-04-23 20:42 UTC
hi there 
just update to 2.2 and got this error:

Error: system.cache: Command to delete /root/.cache/wallpaper
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 84, in execute
    FileUtilities.delete(self.path, self.shred)
  File "/usr/share/bleachbit/FileUtilities.py", line 270, in delete
    logger.info(_("Directory is not empty: %s"), path)
NameError: global name '_' is not defined

**Comment by az0** [comment] 2019-04-23 22:54
This looks like a duplicate of https://github.com/bleachbit/bleachbit/issues/508

Which kind of Linux are you using? Did you install BleachBit from a .rpm or .deb patch on this site?

If you are comfortable with it, you can fix your system by editing a single line in the script `FileUtilities.py` like in change https://github.com/bleachbit/bleachbit/commit/11ebb43a1b67c9d42a73a769fc41e1068f240158. (Don't worry about the tests files.)

**Comment by OLavergne** [comment] 2019-04-23 23:42
Hi Andrew,

Thanks for your fast answer, but it's getting very late here in France,
I'll have a look at your suggestion tomorrow.
Thanks again, cheers
Olivier

Le mer. 24 avr. 2019 à 00:54, Andrew Ziem <notifications@github.com> a
écrit :

**Comment by OLavergne** [comment] 2019-04-24 06:06
Hi Andrew,

This is interesting, I will have a closer look to change that line since
upon a rapid reading of the page the simple evidence did not pop up.  Or
maybe you could be more specific.  In any case, thanks a bunch for
addressing my query, cheers,
Olivier

Le mer. 24 avr. 2019 à 01:41, Olivier Lavergne <ololol60@gmail.com> a
écrit :

**Comment by OLavergne** [comment] 2019-04-25 16:37
Hi Andrew,

If I understand correctly this will be fixed in upcoming version 2.4, so I
wont both to edit the line.  Thanks

Le mer. 24 avr. 2019 à 08:05, Olivier Lavergne <ololol60@gmail.com> a
écrit :

**Comment by az0** [comment] 2019-08-04 18:45
I am closing this because it's a duplicate report, and it has been fixed.

**Closed by az0** 2019-08-04 18:45 UTC
Labels: bug

**Comment by az0** [comment] 2019-10-10 03:37
You could test the fix in the newly-released [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)
