### ISSUE TITLE
DatabaseError: no such table: moz_favicons cleaning Firefox

### ISSUE THREAD

**Issue by UACX64** [bleachbit/bleachbit#235] opened 2017-09-05 10:52 UTC
When the script for History Cleaning is executed it gives following errors:

>  Error in execution of <bleachbit.Command.Function instance at 0x7f10c7354a70>
> Traceback (most recent call last):
>   File "/usr/share/bleachbit/Worker.py", line 84, in execute
>     for ret in cmd.execute(self.really_delete):
>   File "/usr/share/bleachbit/Command.py", line 149, in execute
>     self.func(self.path)
>   File "/usr/share/bleachbit/Special.py", line 281, in delete_mozilla_url_history
>     FileUtilities.execute_sqlite3(path, cmds)
>   File "/usr/share/bleachbit/FileUtilities.py", line 307, in execute_sqlite3
>     '%s: %s' % (Common.decode_str(exc), path))
> DatabaseError: no such table: moz_favicons: /home/user/.mozilla/firefox/b4jshpy5.default/places.sqlite

**Comment by ROCKNROLLKID** [comment] 2017-09-05 16:25
This issue was fixed in some recent commits. It should be resolved for when 2.0 is released.

**Comment by az0** [comment] 2017-09-06 02:59
The second error, as ROCKROLLKID mentioned, was recently fixed.  Because of this and because bug tickets should not be about two issues (here, Firefox, and Chromium), let's consider this issue just about Firefox, so I renamed the title.

That leaves this error `DatabaseError: no such table: moz_favicons`. I retested it today with the latest BleachBit: this is from the git repository, but the code related to the error is the same. I tested it on a clean OpenSUSE Tumbleweed installation with Firefox 52.3. I did not get the error.

I also tested it with Windows 7 and Firefox 55, and I did not get the error.

Any advice on how to reproduce the error?

**Comment by UACX64** [comment] 2017-09-06 09:11
I tested it on several Arch Linux installations and I only get this error when using Bleachbit with Arch Linux. I tried it on a normal system as well as on a fresh installed one.
Currently I am running Arch Linux with Kernel 4.12.10.

I found out that the file that's causing this error is not named moz_favicons but favicons.sqlite.
favicons.sqlite and places.sqlite are both in the folder the error mentioned "/home/user/.mozilla/firefox/profilenumber.default/

About Windows I can't say or test anything because I don't use it.

**Comment by az0** [comment] 2017-09-09 20:37
The table moz_favicons used to be in places.sqlite, and on my system it still has an empty table. Now the data is in the separate file favicons.sqlite, as you pointed out. Perhaps some systems don't have the empty table, and that would cause this error. This is progress

**Comment by UACX64** [comment] 2017-09-09 21:29
Thanks for your answer.
I tried to create a blank table within places.sqlite but it (of course) gives me "DatabaseError: no such column:favicon_id:/home/user/.mozilla/firefox/profilenumber.default/places.sqlite"

If it's possible please upload me your working places.sqlite file, so I can copy it into my folder and see if it's working or not.
Would be interesting.

**Comment by az0** [comment] 2017-12-27 00:27
@UACX64 

I released a fix. Normally during the beta test cycle, I release the source code as a tarball and .rpm and .deb packages for some Linux distributions, but I do not release anything specific to Arch Linux. 

Could you please try to apply this patch https://github.com/bleachbit/bleachbit/commit/fc8e1ddb17b96e9819bd545aec744cb57bfb1da0 or to download the latest version of BleachBit from Git? Git lets you download the [source as a .zip archive](https://github.com/bleachbit/bleachbit/archive/master.zip).

**Comment by az0** [comment] 2017-12-30 23:07
Please test [BleachBit version 1.19 beta](https://www.bleachbit.org/news/bleachbit-119-beta) and reply in this bug ticket with how it goes. Also, please reopen this ticket if the error messages continues.

**Closed by az0** 2017-12-30 23:07 UTC
