### ISSUE TITLE
BleachBit Error: OperationalError: no such table" when cleaning Chrome

### ISSUE THREAD

**Issue by miamibob1954** [bleachbit/bleachbit#1524] opened 2023-08-21 14:44 UTC
For the past few weeks, BleachBit  creates an error when cleaning Chrome browser. It occurs while trying to clean out the User "Web Data" file. Lines 474, 160,106, 87 and 162 - OperationalError: no such table. Please let me know if additional information is required at: mm795@hotmail.com". Thanks...Bobby

**Comment by paolotu1** [comment] 2023-08-27 04:23
I have a similar issue

I will copy / paste the error code

Error: google_chrome.form_history: Function: Limpiar el archivo: C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\Default\Web Data
Traceback (most recent call last):
  File "bleachbit\FileUtilities.pyo", line 474, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Command.pyo", line 160, in execute
  File "bleachbit\Special.pyo", line 106, in delete_chrome_autofill
  File "bleachbit\FileUtilities.pyo", line 482, in execute_sqlite3
sqlite3.OperationalError: no such table: autofill_profile_names: C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\Default\Web Data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bleachbit\Worker.pyo", line 87, in execute
  File "bleachbit\Command.pyo", line 162, in execute
AttributeError: 'OperationalError' object has no attribute 'message'

Thanks for your help

**Comment by miamibob1954** [comment] 2023-08-27 12:49
That is EXACTLY the same error I get and on more than one computer. Wonder if the author/programmer knows about this and will repair?

**Comment by 0pLuS0** [comment] 2023-08-28 01:21
I see several of the same types of reports posted here, these are just a few...

https://github.com/bleachbit/bleachbit/issues/1523

https://github.com/bleachbit/bleachbit/issues/1522

**Comment by miamibob1954** [comment] 2023-08-28 01:44
Thanks for the confirmations. Hope it gets repaired soon!

**Comment by az0** [comment] 2023-08-28 01:52
This is on the short list

**Comment by miamibob1954** [comment] 2023-08-28 02:07
Many thanks Andrew. I am sure you already have enough to keep you busy so we ALL appreciate your efforts!

**Comment by miamibob1954** [comment] 2023-08-28 03:01
New problem upon starting the program (on Windows 11):

The update information does not parse: b"\xc2B\x00\x80l\xad\x99\x7f\xa3:\xf5w\x97d\xb9\xa8th\x9fJ\xac\x93\x03\xb7\xe3M\xbfE\x99\x07\x16xX\x06\x01E,\xb9\x8d9\xb6bB\xd2HV\xdb\xd7~7\xbb}\x84#\xccg\x7f\xa3\xb1\xba\x9f\x8co~\xdd|\xadv|\xf3\xebmH\xa56q\x8c#\xad&g\xfa\xb5z\xfe\x1e\xf8t\xa2\xd9\xfd\xb2[\xcf\x7fn\xb7\xd3u1M\xebV\xa3\xec\x9c\xf5G~o\xe3\xf1\xf2=\xcd\x83\x7f\xaa\x81\x80p@\x1c\x88\xc6\xdf\xc3\xef|v\xfd\xe1\x84\xb4\x9esT\xcd.\x95\x9aZ\xacX\x8d\x1d\xc9\xbcVnjPsb\xecfT@\xa9'\x05/\x9c\rSi\xd8%\x02C\x85 H-\xf7\xd4S\xc2\x14\x90\x9b\x1bI\x15c\xc6\x08!\x93I\x8f\x8c\xb5\xab\x17qA\xaa\x94\xb5\xe7\x1e)\x96\xae\x05\xe6\xd3f\xa5;\xe7\x83_\xf6\xbb\xd9\xfd\xb2[\xb7\xa3&\x9c\xba\x0c\x04\x04\x03\xc4\x01q\xfc\xfc\x9e\x1a\xaeW ,%\xc4\xdcJ\n\xad\x16i\xdcb@\xe5\x10\x93\xc5l\xac\x90\x94L\xc5\xc9\xb5\xa3[\x97NP \x91\x91\x08I@\xce5\x03\xb1JQ\xec1\xc7\xda\xbb\xab@n\xad6\xd3\x02\xd5\xc1\x04\xb2\x96X\xa8\xb6\x1e*\x95\x0ed\x1eS@\xca\xb0\xd3\xfdd|\xf3\xeb\x06"
Traceback (most recent call last):
  File "bleachbit\Update.pyo", line 165, in check_updates
  File "xml\dom\minidom.pyo", line 1970, in parseString
  File "xml\dom\expatbuilder.pyo", line 925, in parseString
  File "xml\dom\expatbuilder.pyo", line 223, in parseString
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 0

**Comment by az0** [comment] 2023-08-29 14:31
The cause of "no such table" is that Google [changed how it stores some data](https://github.com/bleachbit/bleachbit/issues/1518#issuecomment-1684691066). The error does not indicate any harm or damage, but some data in the new location is not yet cleaned. The solution will be to ignore the old table names, if they do not exist, and instead clean the new table names. This will be fixed in the next release.

Because many browsers, such as Brave and Edge, are based on Google Chrome/Chromium, it affects them too, but it does not affect Firefox.

**Comment by az0** [comment] 2023-08-29 14:32
> New problem upon starting the program (on Windows 11):
> 
> The update information does not parse: 

Let's keep the "does not parse" separate from the "no such table." The ticket here (#1524) is about "no such table." You may open your own  new ticket for "does not parse," but there are already several: https://github.com/bleachbit/bleachbit/issues/1528 https://github.com/bleachbit/bleachbit/issues/1527

**Closed** 2023-09-06 04:15 UTC
Labels: bug
