### ISSUE TITLE
Installer is broken in the latest dev build(s)

### ISSUE THREAD

**Issue by ecsjjgg** [bleachbit/bleachbit#1469] opened 2023-02-18 23:29 UTC
The installler is broken in BleachBit-4.4.2.2346 and also in all later dev builds!,

1. Go to https://ci.bleachbit.org/?prefix=dl/4.4.2.2346-master/
2. Download this setup file ( https://ci.bleachbit.org/dl/4.4.2.2346-master/BleachBit-4.4.2.2346-setup.exe )
3. No dialogs is shown/is blank

The error happens Every time when trying to install a dev build later than 4.4.2.2345, which is the last usable one....

 - OS:  Windows 10, and 11

**Comment by az0** [comment] 2023-02-21 15:52
@ecsjjgg thank you for the bug report

[Build 2346](https://ci.appveyor.com/project/az0/bleachbit/builds/46075309) was when PR https://github.com/bleachbit/bleachbit/pull/1457 was merged, which was specifically related to the Windows installer

**Comment by bovirus** [comment] 2023-02-21 16:31
@ecsjjgg 

You are using a very old artifact version.

Please use build 2416 and get it from here

https://ci.appveyor.com/project/az0/bleachbit/builds/46264894/artifacts

@az0 

In the old build the issue is in "Uninstall" module translation issue.
Infact in new version I leave it not translated and I'm searchinga solution for this.
All otehr modules are translated.

**Comment by ecsjjgg** [comment] 2023-02-21 21:50
@bovirus

As I staded in my post ALL LATER builds are also affected, this issue STARTED to appear in build 4.4.2.2346 

This build is also affected:
https://ci.appveyor.com/api/buildjobs/08qj1ni5ngt4f3h8/artifacts/BleachBit-4.4.2.2416-setup.exe

**Comment by bovirus** [comment] 2023-02-21 23:15
@ecsjjgg

I'm not agree.
I tested 2416 and this issues is not available, For me.
Thanks.

**Comment by ecsjjgg** [comment] 2023-02-22 13:50
@bovirus 

Yes that  build works for me!

**Comment by az0** [comment] 2023-03-16 14:21
I just merged Windows installer changes from bovirus into the master branch, and 4.4.2.2438 is building now.

@ecsjjgg Would you check it out?

**Comment by bovirus** [comment] 2023-03-16 14:24
@az0 

Thanks
Please close this issue.

**Closed** 2023-03-16 14:27 UTC
Labels: priority:high, new, platform: windows
