### ISSUE TITLE
Ubuntu 18.04 with bleachit 3 freezes computer

### ISSUE THREAD

**Issue by bulgin** [bleachbit/bleachbit#666] opened 2019-11-02 19:52 UTC
Hello, I am able to run as non-root user but when running either by clicking on the 3.0 desktop icon and entering password for root user, or using command line arguments sudo bleachbit, after running, the computer always freezes.

As well, when successfully running as non-root user, always get a long list of red text errors at the end, such as:
Error: system.memory: Function: Memory
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 88, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 147, in execute
    for func_ret in self.func():
  File "/usr/share/bleachbit/Memory.py", line 306, in wipe_memory
    devices = disable_swap_linux()
  File "/usr/share/bleachbit/Memory.py", line 84, in disable_swap_linux
    raise RuntimeError(stderr.replace("\n", ""))
RuntimeError: swapoff: Not superuser.

**Comment by az0** [comment] 2019-11-03 02:55
This seems to be a duplicate of https://github.com/bleachbit/bleachbit/issues/641 , but for now, I would like to keep both tickets open and separate.

When BleachBIt wipes memory, it requires root privileges, so the "swapoff: not superuser" error is expected when the user does not have root privileges.

When BleachBit wipes memory as root, it forks the process, and the freezing seems to be caused by the other process not finishing. I haven't yet been able to reproduce it, and since BleachBit 2.2, there were no significant changes to memory wiping. There were significant changes to the GUI.

**Comment by mkhon** [comment] 2019-11-10 03:00
I think the computer "freezes" just because swap is disabled.

**Comment by mkhon** [comment] 2019-11-10 03:26
@bulgin how much RAM do you have and how big is swap?
Can you show "free" output before you run bleachbit?

**Comment by mkhon** [comment] 2019-11-10 03:30
@az0 for me Memory cleaning fails with the following errors (depending on RAM size and swap size):

- swapoff failed: Cannot allocate memory
(RAM 1G, swap 2G)
- The child memory-wiping process returned code 9
(RAM 2G, swap 2G - code 9 means the child was killed with SIGKILL)

The latter is OOM killer:

[   79.222498] Out of memory: Kill process 2163 (python) score 1525 or sacrifice child
[   79.222503] Killed process 2163 (python) total-vm:1692764kB, anon-rss:1070964kB, file-rss:0kB, shmem-rss:0kB

**Comment by az0** [comment] 2019-11-10 04:48
@mkhon 
During the memory cleaning process, it is normal for the swap to be disabled and for the OOM killer to kill the child process. The child process intentioanlly changes some settings to attract itself to the OOM killer.

**Comment by az0** [comment] 2019-11-10 16:10
@bulgin 
Max added a patch that fixed  what seems like the same issue for another user. Could you please test it to? You can get it from GitHub from the master branch, or if you prefer, I could build a .deb package.

**Comment by bulgin** [comment] 2019-11-10 16:19
Thanks I'll check it out!

**Comment by az0** [comment] 2019-12-30 00:34
@bulgin 
Have you been able to test? Or, is there a way I can help you test?

Otherwise, I will assume this bug is fixed.

**Comment by az0** [comment] 2020-01-04 23:18
Closing because (1) code fix applied and (2) lack of response from bug reporter

**Closed by az0** 2020-01-04 23:18 UTC
Labels: bounty, bug

**Comment by bulgin** [comment] 2020-01-04 23:25
bug reporter did respond on December 29, 2019. 
      See below:
      
      
        On 12/29/19 7:56 PM, Chip wrote:
        
         Hi Andrew!
            
            It works!  I had previously been asking bleachbit to clean
            files that only root should clean, when running as
            non-root.  Once I unchecked those entries and checked them
            on in the root user bleachbit everything worked out.  I'm
            now using V 3 and enjoying it.  Thanks for the follow up and
            I apologize I didn't let you know this earlier.  I had a
            health issue that distracted me for a few months which is
            now taken care of.
            
            Wishing you a very happy new year!
          
      
      
    
    On 1/4/20 6:18 PM, Andrew Ziem wrote:
    
    
      
      Closing because (1) code fix applied and (2) lack of response
        from bug reporter
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/bleachbit/bleachbit/issues/666?email_source=notifications\u0026email_token=AD6YFY25S3OSKADPRDOIZD3Q4EKMZA5CNFSM4JIHX6EKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIDCLZI#issuecomment-570828261",
"url": "https://github.com/bleachbit/bleachbit/issues/666?email_source=notifications\u0026email_token=AD6YFY25S3OSKADPRDOIZD3Q4EKMZA5CNFSM4JIHX6EKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIDCLZI#issuecomment-570828261",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by az0** [comment] 2020-01-23 04:14
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta)
