### ISSUE TITLE
BleachBit 2.0 breaks Mint Software Manager

### ISSUE THREAD

**Issue by revvedup708** [bleachbit/bleachbit#339] opened 2018-04-28 20:40 UTC
In Mint KDE 18.3 with Mint Software Manager 7.8.9, running BB2.0 as root breaks the Software Manager's graphic interface to where you can click on menu to start it, but it never displays on screen, and the task bar tab closes as well. Reinstalling Software Manager from Synaptic fixes problem until next time BB2.0 is run as root, then another reinstall is required. Note this same issue also happens with BB earlier versions. I'm no brogrammer, so let me know if you need more information.

**Comment by az0** [comment] 2018-04-28 22:37
Are you able to narrow this down to a particular option in BleachBit? Did you clean Localizations?

**Comment by revvedup708** [comment] 2018-04-29 01:51
Hi az0. BB Localizations were cleaned, with US English left as the sole language. I haven't tried cycling through all individual options due to time constraints today. I can say that when I used BB with Mint 18.2 XFCE I never saw the apparent bug. I've run "fix broken packages" in Synaptic today; none were found.

**Comment by AsciiWolf** [comment] 2018-05-23 14:08
This seems to be a MintInstall issue. Try reporting it [here](https://github.com/linuxmint/mintinstall/issues).

**Comment by AsciiWolf** [comment] 2018-06-03 20:38
@revvedup708 This seems to be a MintInstall issue. Report it [here](https://github.com/linuxmint/mintinstall/issues).

**Comment by AsciiWolf** [comment] 2018-06-13 11:54
It looks like that this issue was fixed in Linux Mint 19. I was not able to reproduce it on the latest Linux Mint 19 beta.

**Comment by az0** [comment] 2018-06-13 14:04
Thanks for letting me know

**Closed by az0** 2018-06-13 14:04 UTC
