### ISSUE TITLE
AttributeError: module 'gi' has no attribute 'require_version' on Mac OS X

### ISSUE THREAD

**Issue by ghost** [bleachbit/bleachbit#940] opened 2020-06-13 00:03 UTC
Hi, I'm getting this error running the latest `bleachbit.py` on macOS 10.15

`Traceback (most recent call last):
  File "bleachbit.py", line 43, in <module>
    import bleachbit.GUI
  File "/Users/user/Downloads/bleachbit/bleachbit/GUI.py", line 25, in <module>
    from bleachbit import GuiBasic
  File "/Users/user/Downloads/bleachbit/bleachbit/GuiBasic.py", line 29, in <module>
    gi.require_version('Gtk', '3.0')
AttributeError: module 'gi' has no attribute 'require_version'`

I've installed (and am using) `python3`, `gtk+`, and  `gtk+3` via Homebrew

**Comment by az0** [comment] 2020-06-14 17:53
Sorry, I am not familiar with Mac, but perhaps I can give you general advice that is useful. Some systems might have both Python 2 and Python 3 installed, so please be sure (1) you are using Python 3 to start BleachBit and (2) that you installed the Python 3 version of the GTK libraries. 

Regarding (1), on Ubuntu to start BleachBit, the user must  run `python3 bleachbit.org` because `python bleachbit.org` uses Python 2. Maybe it is similar on Mac.

Next, you might need to also install GI introspection. On openSUSE, this package is called `typelib-1_0-Gtk-3_0. On Ubuntu, it is `gir1.2-gtk-3.0`.

Does this help?

**Comment by gottabeleGIT** [comment] 2020-06-14 18:21
Yes, I did use `python3` to attempt to start BleachBit when I got the error. I installed it, as well as `gtk+` and `gtk+3` from the Homebrew package manager since those seemed to be the only relevant GTK packages available on it.

**Comment by gottabeleGIT** [comment] 2020-06-14 18:27
Here are the available GTK packages from Home-brew:

![Screen Shot 2020-06-14 at 1 23 16 PM](https://user-images.githubusercontent.com/21181118/84600945-ac4ca480-ae42-11ea-9bba-bcd291cee42e.jpg)

Anything else that looks relevant that I should install?

Here is also the info for the `gtk+` and `gtk+3` packages:

![Screen Shot 2020-06-14 at 1 23 39 PM](https://user-images.githubusercontent.com/21181118/84600979-c2f2fb80-ae42-11ea-8f9f-009916940a6e.jpg)
![Screen Shot 2020-06-14 at 1 23 55 PM](https://user-images.githubusercontent.com/21181118/84600983-c5edec00-ae42-11ea-86bb-4e71c6eb8777.jpg)

**Comment by az0** [comment] 2020-06-18 03:09
The `gtk+` package is not needed because that's the old version 2.

Here's another way to approach this: try installing and running another application that uses Python and GTK 3. On Ubuntu, these include:

eog
gedit
gnome-characters
gnome-weather 
gpodder
gramps
mugshot
pitivi
pychess
zim

Would you please try one or two of these? Do they work?

**Comment by gottabeleGIT** [comment] 2020-06-18 03:20
So, `gedit`, `gpodder`, and `gramps` seem to be working properly. The other packages weren't available on Homebrew

**Comment by az0** [comment] 2020-06-18 14:23
Is this python3 installed via homebrew?

**Comment by gottabeleGIT** [comment] 2020-06-18 14:24
Yes

**Comment by kdeldycke** [comment] 2020-06-19 08:26
Got it running with:
```shell-session
$ git clone https://github.com/bleachbit/bleachbit.git   
(...)

$ cd bleachbit
(...)

$ brew install pygobject3
(...)

$ /usr/local/opt/python@3.8/bin/python3.8 ./bleachbit.py --version
BleachBit version 4.0.1
(...)
```

Even the GUI is somewhat working:
```shell-session
$ /usr/local/opt/python@3.8/bin/python3.8 ./bleachbit.py --gui

(bleachbit.py:29612): Gtk-WARNING **: 10:20:59.372: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node text owner GtkProgressBar)

(bleachbit.py:29612): Gtk-WARNING **: 10:20:59.592: Could not load a pixbuf from /org/gtk/libgtk/theme/Adwaita/assets/check-symbolic.svg.
This may indicate that pixbuf loaders or the mime database could not be found.
```

<img width="870" alt="Screen Shot 2020-06-19 at 10 21 20" src="https://user-images.githubusercontent.com/159718/85112911-b1c93680-b216-11ea-8e00-28576a99ba40.png">

The issue is that `pygobject3` is installed for Python 3.8, the later is [keg-only](https://discourse.brew.sh/t/how-to-default-python-3-8-on-my-mac-using-homebrew/7050), and the default Python 3 is 3.7:
```
$ brew info python@3.8
python@3.8: stable 3.8.3 (bottled) [keg-only]
(...)
python@3.8 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.
(...)

$ python --version
Python 3.7.7

$❯ ls -lah /usr/local/lib/python3.8/site-packages/
(...)
drwxr-xr-x 20 user staff  640 Jun 19 08:52 gi/
(...)
```

**Comment by kdeldycke** [comment] 2020-06-19 08:28
BTW I'm trying to package BleachBit for brew but that's not really straightforward. 😞

**Comment by kdeldycke** [comment] 2020-06-19 09:24
FYI, I'm trying to package BleachBit for brew at: https://github.com/Homebrew/homebrew-core/pull/56538

**Comment by az0** [comment] 2021-03-14 20:34
The user who reported the original issue (`module gi has no attribute`...) no longer has a GitHub account. (It's the "ghost" account now.) Also, it's exciting that kdeldycke made so much progress. So, I am closing the issue.

If something else comes up, let's open a new ticket

**Closed by az0** 2021-03-14 20:34 UTC
