### ISSUE TITLE
Error message after using 2.2 on Linux system

### ISSUE THREAD

**Issue by Linux-Johnston** [bleachbit/bleachbit#646] opened 2019-10-10 02:40 UTC
Hello,

I use to get the following error message when using BB 2.2 as a root on Linux 19.2: 

Error: system.memory: Function: Arbeitsspeicher
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 147, in execute
    for func_ret in self.func():
  File "/usr/share/bleachbit/Memory.py", line 302, in wipe_memory
    wipe_swap_linux(devices, proc_swaps)
  File "/usr/share/bleachbit/Memory.py", line 274, in wipe_swap_linux
    logger.info(_("Wiping the swap device %s."), device)
UnboundLocalError: local variable '_' referenced before assignment

It's probably some kind of problem when trying to delete the working memory (RAM). Any help?

**Comment by az0** [comment] 2019-10-10 02:49
This is a duplicate of https://github.com/bleachbit/bleachbit/issues/575 . Please test the fix in [BleachBit 2.3 beta](https://www.bleachbit.org/news/bleachbit-23-beta)

**Comment by az0** [comment] 2019-10-13 16:53
If the problem persists, please open this ticket. If BleachBit 2.3 beta fixes it, please add a comment to confirm it was fixed.

**Closed by az0** 2019-10-13 16:53 UTC
Labels: bug

**Comment by Linux-Johnston** [comment] 2019-10-15 01:05
Root mode seems to work alright in BB 2.3, problem persists when starting 'normal' mode:

Fehler: system.memory: Function: Arbeitsspeicher
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 88, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 147, in execute
    for func_ret in self.func():
  File "/usr/share/bleachbit/Memory.py", line 306, in wipe_memory
    devices = disable_swap_linux()
  File "/usr/share/bleachbit/Memory.py", line 84, in disable_swap_linux
    raise RuntimeError(stderr.replace("\n", ""))
RuntimeError: swapoff: Not superuser.

**Comment by az0** [comment] 2019-10-16 03:56
Thanks for checking. Cleaning memory always requires root privileges, so that error is expect. It's the Linux security model that normal users are not allowed to disable the swapfile.
