### ISSUE TITLE
cannot compile bleachbit from source due to gtk error

### ISSUE THREAD

**Issue by FrostKnight** [bleachbit/bleachbit#540] opened 2019-04-18 17:47 UTC
I recall looking in the issues and finding an issue,

https://github.com/bleachbit/bleachbit/issues/413

like this one, but I wondered, is there an alternate way to do this:

pkexec /usr/bin/python2.7 /usr/bin/bleachbit 

when compiling the source code to install bleachbit, in archlinux?

I have certain reasons for doing this without their repo, one of which being, I am using a forked version of archlinux.

**Comment by az0** [comment] 2019-04-18 18:16
What is the exact error? Does it work without pkexec?

**Comment by FrostKnight** [comment] 2019-04-18 23:36
The exact error is this: Traceback (most recent call last):
  File "bleachbit.py", line 38, in <module>
    import gtk
ModuleNotFoundError: No module named 'gtk'

and I have gtk2 and gtk3 installed.  odd but true.

**Comment by az0** [comment] 2019-04-19 14:44
What if you run it without pkexec like `/usr/bin/python2.7 /usr/bin/bleachbit`?

**Comment by FrostKnight** [comment] 2019-04-19 18:10
It loads the wrong bleachbit or no bleachbit if I try. Though I should also add, its not even installed yet. Because I cannot seem to install it for the above reasons.

**Comment by FrostKnight** [comment] 2019-04-19 18:11
It depends on if I have bleachbit installed already before I compile, but in any case, its not willing to compile right now.
its weird.

**Comment by az0** [comment] 2019-05-01 23:17
What do you mean "wrong bleachbit"?

Also, it would help if you could explain "no bleachbit". In other words, does it give an error message? If so, what is the error mesage?

You mentioned you cannot install it. When you try, which error message do you get?

**Comment by FrostKnight** [comment] 2019-05-01 23:24
Well, I meant I was trying to install bleachbit 2.0.  But I cannot make it run here: /usr/bin/python2.7 /usr/bin/bleachbit
That would imply, I have it installed. or at least that is what I thought anyways. 
This error is pretty much identical to my problem: https://github.com/bleachbit/bleachbit/issues/413

**Comment by FrostKnight** [comment] 2019-05-01 23:27
If you'd like I can try it with your newest version. Maybe it will do better that way.

**Comment by az0** [comment] 2019-05-01 23:40
The GTK error can be caused by a few things, so the cause may not be the same as #413.

If you get the GTK error as a normall, non-root user running `/usr/bin/python2.7 /usr/bin/bleachbit`, then the next step is to verify your system has PyGTK 2 installed. I don't use Arch, but a web search led me to this page: https://www.archlinux.org/packages/extra/x86_64/pygtk/

Remarkably, bleachbit is the first "required by" package on that page. :)

**Comment by az0** [comment] 2019-05-01 23:41
By the way, I do recommend BleachBit version 2.2, but it might not solve your problem.

**Comment by FrostKnight** [comment] 2019-05-01 23:44
PyGTK2? hmm... pygtk2 might be why, I have a package called pygtk, but not gtk2... hmm... 

Well, that's bad... any recommendation on a version which would work, besides the one im using 1.12?

**Comment by topas-rec** [comment] 2020-04-25 11:28
Tried to install BleachBit through package manager in Debian 10.3 today and it doesn't start with the error mentioned above:

`~$ bleachbit

Traceback (most recent call last):
  File "/usr/bin/bleachbit", line 38, in <module>
    import gtk
ModuleNotFoundError: No module named 'gtk'
`

**Comment by az0** [comment] 2020-04-25 14:09
> Tried to install BleachBit through package manager in Debian 10.3 today and it doesn't start with the error mentioned above:
> 
> `~$ bleachbit
> 
> Traceback (most recent call last):
> File "/usr/bin/bleachbit", line 38, in 
> import gtk
> ModuleNotFoundError: No module named 'gtk'
> `
I think this your situation is different than issue 540, so I created a separate issue ticket https://github.com/bleachbit/bleachbit/issues/894 . In other, please give me some more details. I'll write the questions there.

Also, I am closing 540 because the discussion is a year old

**Closed by az0** 2020-04-25 14:09 UTC

**Comment by FrostKnight** [comment] 2020-04-27 13:15
> > Tried to install BleachBit through package manager in Debian 10.3 today and it doesn't start with the error mentioned above:
> > `~$ bleachbit
> > Traceback (most recent call last):
> > File "/usr/bin/bleachbit", line 38, in
> > import gtk
> > ModuleNotFoundError: No module named 'gtk'
> > `
> > I think this your situation is different than issue 540, so I created a separate issue ticket #894 . In other, please give me some more details. I'll write the questions there.
> 
> Also, I am closing 540 because the discussion is a year old

Oh sorry, I forgot to mention, my error is solved because, I had to change in compiling, /usr/local to /usr in the prefix to get it to work, no worries, its solved anyhow to sum it up. :)
