### ISSUE TITLE
The user interface is garbled.

### ISSUE THREAD

**Issue by tyf2018** [bleachbit/bleachbit#1297] opened 2021-11-08 12:14 UTC
The user interface is garbled.

**Expected behavior**
The user interface is displayed normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/56342788/140740148-6a40286b-01d0-4e03-ba1d-0d45b3264a4f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - BleachBit version 4.4

**Comment by az0** [comment] 2021-11-09 00:10
Duplicate of https://github.com/bleachbit/bleachbit/issues/1207 fixed in [BleachBit 4.4.1 beta](https://www.bleachbit.org/news/bleachbit-441-beta). Please upgrade, and if issue persists, reopen this issue.

**Closed by az0** 2021-11-09 00:10 UTC
Labels: new
