### ISSUE TITLE
exception in get_autostart_path() when opening settings

### ISSUE THREAD

**Issue by Jon-guy30** [bleachbit/bleachbit#383] opened 2018-09-01 13:12 UTC
What have I done? When I open up the program's settings it throws an error. It didn't used to do that. I hope I haven't removed something critical. I've been using bleachbit normally. The program still works, but every time I open the settings window I get this.

![bleachbit unid error](https://user-images.githubusercontent.com/10241225/44946222-ce00a700-ade7-11e8-9d89-b9189fd382f4.PNG)

"Undefined error".

![the error](https://user-images.githubusercontent.com/10241225/44946223-d6f17880-ade7-11e8-916e-6fb143618b2e.PNG)

Bleachbit version 2.0
Windows 8.1 x64

Also when I download a new copy the same thing happens.

**Comment by az0** [comment] 2018-09-02 02:26
Please try running the [BleachBit Debugging Terminal](https://docs.bleachbit.org/doc/troubleshooting.html). If you search the start menu for it, you should find it there. (You do not need to use the command line.) When you run in this mode, there will be a "black DOS window" with additional information. Please check the "DOS window" for extra details, and let me know how it goes. Also, if you need help with these steps, let me know.[](url)

**Comment by Jon-guy30** [comment] 2018-09-02 16:50
Here you go!

![error more info](https://user-images.githubusercontent.com/10241225/44958467-2dd27d00-aed0-11e8-892c-9fdc3a183fbd.PNG)

![error more info 2](https://user-images.githubusercontent.com/10241225/44958469-3460f480-aed0-11e8-90bb-94491fcdd706.PNG)

**Comment by az0** [comment] 2021-03-14 20:03
@Jon-guy30 
Thank you for your patience with my overdue reply. I'm not sure how to reproduce the problem.

Are still on Windows 8.1? Do you still have this error with [BleachBit version 4.2.0 (final)](https://www.bleachbit.org/download) or the [latest CI build](https://ci.bleachbit.org/)?

**Comment by abitrolly** [comment] 2021-11-03 09:49
The 2.0 version looks dated

**Comment by az0** [comment] 2021-11-04 02:46
There has been no reply for one-half year,  and the issue is not reproducible, so I am closing this.

@Jon-guy30 
If you reproduce this on the latest stable or latest beta version, please reopen this issue ticket.

@abitrolly 
Thank you for pointing out this issue that had an easy action

**Closed by az0** 2021-11-04 02:46 UTC
