### ISSUE TITLE
[Multiple Issues] Portable version seems not be able to use native CleanerML cleaners

### ISSUE THREAD

**Issue by Tobias-B-Besemer** [bleachbit/bleachbit#675] opened 2019-11-06 05:12 UTC
In my test the portable version wasn't able to download community cleaners.
Don't know why!

**Comment by az0** [comment] 2019-11-06 05:14
Please look for error messages, possibily in `bleachbit_console.exe` or with debug mode on.

**Comment by Tobias-B-Besemer** [comment] 2019-11-06 05:42
No I run into other probs...

![2019-11-06 06_41_21-BleachBit](https://user-images.githubusercontent.com/11881073/68271401-a0a13000-0060-11ea-9457-35ef80f643a0.jpg)

![2019-11-06 06_41_39-Administrator_ C__Windows_system32_cmd exe - bleachbit_console exe  --gui --debu](https://user-images.githubusercontent.com/11881073/68271405-a565e400-0060-11ea-988b-c80fa99c5367.jpg)

**Comment by az0** [comment] 2019-11-07 04:39
I tried with the latest Git revision (not installed/not built) and with the official 3.0 portable version. Each downloaded the latest winapp2.ini, but I can't reproduce this. 

Could you please try to delete the winapp2.ini and try again? It is using the copy under `i:\work\...`

**Comment by ediowar** [comment] 2019-11-08 12:59
>  It is using the copy under `i:\work\...`
Maybe because of uncommon path?

**Comment by Tobias-B-Besemer** [comment] 2019-11-11 10:12
For the notes: There's a encoding issue with WinApp2.ini!
Look: https://github.com/bleachbit/bleachbit/issues/673

**Comment by Tobias-B-Besemer** [comment] 2019-11-11 10:25
So if we exclude the parsing prob, the following remains:
- Output about loading language gets shown twice (mentioned that somewhere else, but can't remember where);
- After checking "load community cleaners" you have to close and reopen BB that the cleaners get loaded;
- Starting BB with bleachbit_console.exe still don't show the WinApp2.ini cleaners;
- Starting with bleachbit.exe shows community cleaners, but not the native one.

Screenshots:
![2019-11-11 11_12_33-Portable version seems not be able to download community cleaners · Issue #675 ·](https://user-images.githubusercontent.com/11881073/68579947-996d8e00-0475-11ea-953c-b58dc88b9595.jpg)

Note: After some tries I get with the console the same results as with the normal EXE...

**Comment by Tobias-B-Besemer** [comment] 2019-11-11 10:27
...and deleting WinApp2.ini and restart with console gives me this:
![2019-11-11 11_26_27-Portable version seems not be able to download community cleaners · Issue #675 ·](https://user-images.githubusercontent.com/11881073/68580231-34fefe80-0476-11ea-9a2e-0c7447afc253.jpg)

**Comment by Tobias-B-Besemer** [comment] 2019-11-11 10:31
...same if I delete Winapp2.ini and start with the normal EXE!

Looks like multiple issues at ones... but I guess better analyze and QC can be done after some of the issues are fixed...

**Comment by Tobias-B-Besemer** [comment] 2019-11-14 06:38
I found an other issue ATM that "feel at bit wrong" for me...
I thought I can work-around the upper issues with just turning community cleaners off, 'cause it seems to me, that the issues come from there...
...but it seems BB read and interpret the community cleaner file (WinApp2.ini) anyway if it exist, even when they are turned off! BB just don't show and use them!
So the question for me is, e.g. to have a chance to make a work-around if anything with WinApp2.ini goes wrong, shouldn't BB not ignore the file complitely, if community cleaners are turned off in the settings?

**Comment by Tobias-B-Besemer** [comment] 2019-11-14 06:57
First, for the notes, I make a PR to fix WinApp2.ini here: https://github.com/bleachbit/winapp2.ini/pull/15

**Comment by Tobias-B-Besemer** [comment] 2019-11-14 07:12
Next prob: Turning off the community cleaners with the fixed version of WinApp2.ini turns of the native cleaners, not the WinApp2.ini cleaners! Means: Turning off turn off the opposite cleaners then intended !!!
I will show this in the attached screenshot...
@az0, seems BB Portable is totally screwed up! IMHO you should make a patch release of it ASAP !!!

![2019-11-14 07_56_05-I__work_Cleaner_Apps_BleachBit-3 0-portable (2)_BleachBit-Portable](https://user-images.githubusercontent.com/11881073/68834627-839adb80-06b6-11ea-9b43-d3ae28618285.jpg)

**Comment by Tobias-B-Besemer** [comment] 2019-11-14 07:15
OK, I had a look on it in debugging mode... and it seems there is "/share" in the path missing!

![2019-11-14 08_08_19-BleachBit](https://user-images.githubusercontent.com/11881073/68834764-cc529480-06b6-11ea-85ef-03cde4ce9574.jpg)

![2019-11-14 08_08_50-Administrator_ C__Windows_system32_cmd exe - bleachbit_console exe  --gui --debu](https://user-images.githubusercontent.com/11881073/68834773-d1afdf00-06b6-11ea-8e7d-0025c18df2ca.jpg)

Move the "cleaner" folder one level up, out of "share", solves the situation!

**Comment by Tobias-B-Besemer** [comment] 2019-11-14 07:19
Other issue, but I add it also here...
As German is completely translated... Is the string "elapsed time" not translatable ???

![2019-11-14 08_18_09-BleachBit](https://user-images.githubusercontent.com/11881073/68835056-84803d00-06b7-11ea-88a6-fa720c551077.jpg)

**Comment by Tobias-B-Besemer** [comment] 2019-11-14 07:20
...and what's about "seconds" behind it ??? It's also English... :-/

**Comment by Tobias-B-Besemer** [comment] 2019-11-14 07:23
...and pressing the "Abort" button, shows this part two times:

![2019-11-14 08_22_25-BleachBit](https://user-images.githubusercontent.com/11881073/68835304-04a6a280-06b8-11ea-9e6f-6b69cb32dbdc.jpg)

**Comment by Tobias-B-Besemer** [comment] 2019-11-14 07:25
And one more, if I'm already collecting small issues here... ^^

The menu button is the only one who have no tool-tip !!!

![2019-11-14 08_24_17-Portable version seems not be able to download community cleaners · Issue #675 ·](https://user-images.githubusercontent.com/11881073/68835431-59e2b400-06b8-11ea-97f4-6c6494be24cc.jpg)

**Comment by az0** [comment] 2019-11-16 04:50
Today I published a new Winapp2.ini. Did this help?

**Comment by Tobias-B-Besemer** [comment] 2019-11-18 17:40
Yes, with the WinApp2.ini part...
...but there are a lot of other bugs, too!
So e.g. the native cleaners doesn't get loaded with the default file structure...

**Comment by az0** [comment] 2019-12-29 19:06
I am closing this issue because of two reasons

A. Some of it is fixed and 
B. A best practice of bug management is "Open a new bug report for each issue" (e.g., it's Firefox's [first guideline](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines))

**Closed by az0** 2019-12-29 19:06 UTC
Labels: bug

**Comment by Tobias-B-Besemer** [comment] 2020-01-21 02:34
To B.: Yeah, but making 20 bug reports, each one for a minor prob, doesn't help also, or? I check later if and what is IMHO still open...

**Comment by az0** [comment] 2020-01-21 03:46
If the problem is very minor, perhaps it is best not to report it. There's a limited capacity to fix bugs, and it's best to focus on the most severe bugs.
