### ISSUE TITLE
My mane Disk keeps going max win i scan on the Bleachbit exe

### ISSUE THREAD

**Issue by Robertpuggle** [bleachbit/bleachbit#930] opened 2020-05-27 20:30 UTC
It will be lease and then it's maxing out of space can the Bleachbit team update the exe by 4.0.2 installer and the update paces the bug out and add a remove Junk files from uninstalled programs

**Comment by Robertpuggle** [comment] 2020-05-27 20:50
![Capture](https://user-images.githubusercontent.com/40573140/83070942-d83dec80-a031-11ea-930b-9d139be9536c.PNG)

**Comment by ediowar** [comment] 2020-05-27 23:00
> Q: I closed BleachBit while it was working for a long time, and now my hard drive is full. How do I fix it?

[Frequently Asked Questions](https://docs.bleachbit.org/doc/frequently-asked-questions.html)

**Comment by Robertpuggle** [comment] 2020-05-28 13:59
@ediowar I did was not closed the exe I was running it and not these> I closed BleachBit while it was working for a long time, and now my hard drive is full.

**Comment by ediowar** [comment] 2020-05-28 22:22
https://github.com/bleachbit/bleachbit/issues/892#issuecomment-619571135

**Comment by Robertpuggle** [comment] 2020-06-07 18:32
My Blechbit is not sorce code @ediowar

**Comment by ediowar** [comment] 2020-06-07 18:40
@Robertpuggle 
> Not all huge files were created by BleachBit. The files it created have very long names made of random characters.

https://github.com/bleachbit/bleachbit/issues/892#issuecomment-619571135

**Comment by Robertpuggle** [comment] 2020-06-07 19:02
@ediowar  Tryed to find the plase in my folder to fin Blechbit big or the mecond file here

o add on to what ediowar wrote, you can try this command to look BleachBit's large files that apparently it wasn't able to clean because it was shutdown prematurely. Not all huge files were created by BleachBit. The files it created have very long names made of random characters.

find / -type f -size +1G

**Comment by az0** [comment] 2021-03-14 21:16
From what I read here, Robertpuggle had an issue with his drive being full after cleaning with BleachBit, but then he found the files, so the issue is resolved. Therefore, I will close this ticket. Thank you, ediowar, for your help.

**Closed by az0** 2021-03-14 21:16 UTC
