### ISSUE TITLE
Checking Memory keeps BB from closing

### ISSUE THREAD

**Issue by ediowar** [bleachbit/bleachbit#641] opened 2019-10-06 11:39 UTC
In a program running from latest source by a command with sudo, when Memory is checked, when you try to close the program after cleaning, a message box appears: This window is not responding. Do you want to force the application to exit, or wait for it to respond? When you select to wait, the program does not close until you close the terminal or select to force the application to exit.

**Comment by az0** [comment] 2019-10-06 18:06
I tried it on my system, and I didn't notice any freeze.

The freeze could happen when cleaning memory because BleachBit forks its process, and maybe the child process is not finished.

Could you please run BleachBit in a console like this?
`sudo python bleachbit.py --debug --gui &> /tmp/bleachbit.log`

Then please upload the log, in case there are additional details that might help.

**Comment by ediowar** [comment] 2019-10-06 21:00
[bleachbit.log](https://github.com/bleachbit/bleachbit/files/3694831/bleachbit.log)
When you select to force the application to exit, processes ID 3030, 3031, 3066 continue to remain in memory. Only after the terminal is closed do they end.
![Screenshot from 2019-10-06 23-19-12](https://user-images.githubusercontent.com/44164186/66275699-e3ba8880-e893-11e9-9ec8-8900dfb11a14.png)
![Screenshot from 2019-10-06 23-19-45](https://user-images.githubusercontent.com/44164186/66275752-72c7a080-e894-11e9-90bf-3b87fd1a933b.png)
![Screenshot from 2019-10-06 23-20-06](https://user-images.githubusercontent.com/44164186/66275754-778c5480-e894-11e9-92ea-c05ef41f14ba.png)
![Screenshot from 2019-10-06 23-20-59](https://user-images.githubusercontent.com/44164186/66275755-7b1fdb80-e894-11e9-9965-90bbe795adad.png)
![Screenshot from 2019-10-06 23-22-46](https://user-images.githubusercontent.com/44164186/66275756-7ce99f00-e894-11e9-8375-c93dfc1f4cc6.png)
![Screenshot from 2019-10-06 23-40-30](https://user-images.githubusercontent.com/44164186/66275760-7eb36280-e894-11e9-9084-cfad1e9ec501.png)

**Comment by ediowar** [comment] 2019-10-14 12:38
another [bleachbit.log](https://github.com/bleachbit/bleachbit/files/3724444/bleachbit.log)

**Comment by az0** [comment] 2019-11-03 02:56
Does it freeze with just the CLI (i.e., not the GUI)?

`sudo python bleachbit.py --debug --clean system.memory &> /tmp/bleachbit.log`

**Comment by ediowar** [comment] 2019-11-03 18:14
No.
[bleachbit.log](https://github.com/bleachbit/bleachbit/files/3801925/bleachbit.log)

**Comment by mkhon** [comment] 2019-11-10 03:26
@ediowar which Linux distro and version are you running?
Also, how much RAM do you have and how big is your swap?

**Comment by mkhon** [comment] 2019-11-10 03:36
I reproduced this (RAM 4G, swap 2G):

` 2341 pts/1    S+     0:00  |       \_ sudo python bleachbit.py
 2343 pts/1    Sl+    0:04  |           \_ python bleachbit.py
 2406 pts/1    SN+    0:01  |               \_ python bleachbit.py`

child process is in futex():

`[Sun Nov 10 03:33:54] root@ubuntu-1804:~# strace -p 2406
strace: Process 2406 attached
futex(0x7f2ac0001c20, FUTEX_WAIT_PRIVATE, 0, NULL^Cstrace: Process 2406 detached
 <detached ...>
`

**Comment by mkhon** [comment] 2019-11-10 03:47
Child inherits some of the fd's from the parent process that I think should not be there:

```
python  2642 fjoe    0u      CHR              136,1      0t0      4 /dev/pts/1
python  2642 fjoe    1u      CHR              136,1      0t0      4 /dev/pts/1
python  2642 fjoe    2u      CHR              136,1      0t0      4 /dev/pts/1
python  2642 fjoe    3u  a_inode               0,13        0   9567 [eventfd]
python  2642 fjoe    4u     unix 0xffff942ff8f6a400      0t0  42520 type=STREAM
python  2642 fjoe    5u  a_inode               0,13        0   9567 [eventfd]
python  2642 fjoe    6u     unix 0xffff9430173a9800      0t0  42488 type=STREAM
python  2642 fjoe    7u  a_inode               0,13        0   9567 [eventfd]
python  2642 fjoe    8u     unix 0xffff9430173a8800      0t0  42493 type=STREAM
python  2642 fjoe    9u  a_inode               0,13        0   9567 [eventfd]
python  2642 fjoe   11r      CHR                1,9      0t0     11 /dev/urandom
```

**Comment by mkhon** [comment] 2019-11-10 03:59
I think it hangs because cleanup handlers are called which try to tear-down GTK/X11 stuff in child.
Fixed in #686.

**Comment by az0** [comment] 2019-11-10 04:50
@mkhon 
Those are interesting observations.

@ediowar 
Would you please test Max's pull request? Can you get his code from GitHub, or would you like me to build a .deb package?

**Comment by ediowar** [comment] 2019-11-10 10:42
Ubuntu 16.04, RAM 4G, swap 4,2 GB
Tested Max's pull request on latest Git revision (not installed/not built). It fix the bug.

**Closed** 2019-11-10 16:06 UTC
Labels: bounty

**Comment by az0** [comment] 2020-01-23 04:22
I published this fix in [BleachBit 3.1.0 beta](https://www.bleachbit.org/news/bleachbit-31-beta). Perhaps you could test and write back here with any comments about how it addresses your issue.

**Comment by ediowar** [comment] 2020-02-19 14:14
In BleachBit-3.2.0-portable the issue does not reproduce.

**Comment by az0** [comment] 2020-02-19 14:14
Great!
