### ISSUE TITLE
Memory & Yum Errors

### ISSUE THREAD

**Issue by 2635599** [bleachbit/bleachbit#600] opened 2019-08-04 11:33 UTC
checked the memory and yum cleaners this morning and hit delete when done it had two errors.

```
 memory:
 
 Error: system.memory: Function: Memory
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 147, in execute
    for func_ret in self.func():
  File "/usr/share/bleachbit/Memory.py", line 302, in wipe_memory
    wipe_swap_linux(devices, proc_swaps)
  File "/usr/share/bleachbit/Memory.py", line 274, in wipe_swap_linux
    logger.info(_("Wiping the swap device %s."), device)
UnboundLocalError: local variable '_' referenced before assignment
```

```
yum: clean all:

Error: yum.clean_all: Function: yum clean all
Traceback (most recent call last):
  File "/usr/share/bleachbit/Worker.py", line 83, in execute
    for ret in cmd.execute(self.really_delete):
  File "/usr/share/bleachbit/Command.py", line 144, in execute
    func_ret = self.func()
  File "/usr/share/bleachbit/Unix.py", line 683, in yum_clean
    run_cleaner_cmd('yum', args, '^unused regex$', invalid)
  File "/usr/share/bleachbit/Unix.py", line 605, in run_cleaner_cmd
    universal_newlines=True, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['yum', '--enablerepo=*', 'clean', 'all']' returned non-zero exit status 1
```

kubuntu 19.04 64 bir, kernel 5.2.1

**Comment by az0** [comment] 2019-08-04 15:05
In the future please don't file unrelated issues together because it makes it hard to manage. 

The first issue (UnboundLocalErrror) looks like a duplicate of https://github.com/bleachbit/bleachbit/issues/575 which was fixed

For the second issue, are you running BleachBit with sudo or root privileges? If so, please run this command from a terminal to check for other issues

`sudo yum --repoenable=* clean all`

**Comment by 2635599** [comment] 2019-08-04 15:11
not to be rude but i will file a single issue as just that., i got BOTH of those on my last run of bleachbit as root now that said i get the following running your command.

```
mg2635599@2635599s-Kubuntu:~$ sudo yum --repoenable=* clean all
[sudo] password for mg2635599: 
Usage: yum [options] COMMAND

List of Commands:

check          Check for problems in the rpmdb
check-update   Check for available package updates
clean          Remove cached data
deplist        List a package's dependencies
distribution-synchronization Synchronize installed packages to the latest available versions
downgrade      downgrade a package
erase          Remove a package or packages from your system
groups         Display, or use, the groups information
help           Display a helpful usage message
history        Display, or use, the transaction history
info           Display details about a package or group of packages
install        Install a package or packages on your system
list           List a package or groups of packages
load-transaction load a saved transaction from filename
makecache      Generate the metadata cache
provides       Find what package provides the given value
reinstall      reinstall a package
repolist       Display the configured software repositories
resolvedep     Determine which package provides the given dependency
search         Search package details for the given string
shell          Run an interactive yum shell
update         Update a package or packages on your system
upgrade        Update packages taking obsoletes into account
version        Display a version for the machine and/or available repos.


Command line error: no such option: --repoenable
```

**Comment by az0** [comment] 2019-08-06 03:43
I noticed you use Kubuntu. Normally package management on Kubuntu systems is done through APT instead of YUM, so unless you have a special need for YUM, what do you think about not checking the YUM checkbox?

**Comment by 2635599** [comment] 2019-08-06 11:53
don't remember off the top of my head what i installed via yum but for mow i'll just leave the vacuum part checked till you figure out the issue with the other.

**Comment by allanromanreyes** [comment] 2020-12-27 21:38
Still getting Error: system.memory: Function: Memory eroor when running Administrator cleaning on Raspberry Pi 4B 8GB:

error block:
Error: system.memory: Function: Memory
Traceback (most recent call last):
File "/usr/share/bleachbit/Worker.py", line 87, in execute
for ret in cmd.execute(self.really_delete):
File "/usr/share/bleachbit/Command.py", line 145, in execute
for func_ret in self.func():
File "/usr/share/bleachbit/Memory.py", line 315, in wipe_memory
fill_memory_linux()
File "/usr/share/bleachbit/Memory.py", line 143, in fill_memory_linux
buf = '\x00' * allocbytes
OverflowError: cannot fit 'int' into an index-sized integer
Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space.[Errno 13] Permission denied: '/root/.cache': Function: Overwrite free disk space /root/.cache
Disk space recovered: 13MiB
Files deleted: 542
Special operations: 6
Errors: 2

Diagnostics:
BleachBit version 4.1.1
Git revision 940c1c39
GTK version 3.24.5
GTK theme = PiXflat
GTK icon theme = PiXflat
GTK prefer dark theme = True
SQLite version 3.27.2
local_cleaners_dir = None
locale_dir = /usr/share/locale/
options_dir = /root/.config/bleachbit
personal_cleaners_dir = /root/.config/bleachbit/cleaners
system_cleaners_dir = /usr/share/bleachbit/cleaners
locale.getdefaultlocale = ('en_US', 'UTF-8')
os.getenv('DESKTOP_SESSION') = None
os.getenv('LOGNAME') = root
os.getenv('USER') = root
os.getenv('SUDO_UID') = None
os.path.expanduser('~') = /root
platform.linux_distribution() = ('debian', '10.7', '')
platform.platform = Linux-5.4.79-v7l+-armv7l-with-debian-10.7
platform.version = #1373 SMP Mon Nov 23 13:27:40 GMT 2020
sys.argv = ['/usr/bin/bleachbit']
sys.executable = /usr/bin/python3
sys.version = 3.7.3 (default, Jul 25 2020, 13:03:44)
[GCC 8.3.0]
file = /usr/share/bleachbit/Diagnostic.py

**Comment by az0** [comment] 2020-12-28 15:24
@allanromanreyes 

> Still getting Error: system.memory: Function: Memory eroor when running Administrator cleaning on Raspberry Pi 4B 8GB:

You posted your problem in two issue tickets, but neither issue ticket is about the same cause as yours. Please open a new issue ticket

https://github.com/bleachbit/bleachbit/issues/575#issuecomment-751748751

**Comment by az0** [comment] 2021-03-14 20:31
I am closing with these resolutions

UnboundLocalError: fixed in https://github.com/bleachbit/bleachbit/issues/575

CalledProcessError: Ubuntu users should generally _not_ enable the Yum cleaner

OverflowError: This does not belong under this same ticket because combining unrelated issues under one ticket makes them harder to manage, so please create a separate ticket

**Closed by az0** 2021-03-14 20:31 UTC
