### ISSUE TITLE
UnicodeDecodeError cleaning Google Chrome with BleachBit 4.0.0

### ISSUE THREAD

**Issue by gzu88bv** [bleachbit/bleachbit#890] opened 2020-04-24 08:00 UTC
Upgraded to version 4.0.0
running on Windows 10 Pro
see red error on enclosed file
upgraded from version 3.0.0
![2020-04-24_144236](https://user-images.githubusercontent.com/26356673/80189030-372bd280-863c-11ea-9966-318a251b7cdd.png)

**Comment by gzu88bv** [comment] 2020-04-24 08:01
Have no idea to get rid of error

**Comment by az0** [comment] 2020-04-24 14:08
@gzu88bv 

You closed this issue. Normally that means the problem is resolved, and no more action is needed. I think that's not the case, so I will reopen the issue.

The problem is BleachBit is reading a Google Chrome file with the wrong encoding, so it cannot read it. This means one file cannot be cleaned, but it does not cause any damage. Your issue is the same as another user's https://github.com/bleachbit/bleachbit/issues/874

I'll work on fixing it. Until then, you can choose to ignore this error, or you can downgrade to the previous version BleachBit 3.2.0.

**Comment by gzu88bv** [comment] 2020-04-24 15:26
I was not too familiar with GitHub when reporting the bug, but do
appreciate your valuable time and answer. Just sent you a few dollars for a
beer or two over the weekend. Kind regards Hans
He

Andrew Ziem <notifications@github.com> schrieb am Fr., 24. Apr. 2020, 21:08:

**Comment by az0** [comment] 2020-06-25 03:09
@gzu88bv 
When you get a chance, would you please download version 4.0.1.1660 or newer from https://ci.bleachbit.org/ and test it? It should be there in ~15 minutes. Afterwards, you should not have have the UnicodeDecodeError when cleaning Google Chrome

**Comment by gzu88bv** [comment] 2020-06-25 04:40
Hello,

Installed version 4.0.1.1662 which now runs like a charm and error is 
gone.
My Windows corresponds to file attached which has not been updated to 
windows 10 pro vers. 2004 yet.

------ Originalnachricht ------
Von: "Andrew Ziem" <notifications@github.com>
An: "bleachbit/bleachbit" <bleachbit@noreply.github.com>
Cc: "gzu88bv" <suizo_at_large@bluewin.ch>; "Mention" 
<mention@noreply.github.com>
Gesendet: 25.06.2020 10:09:54
Betreff: Re: [bleachbit/bleachbit] UnicodeDecodeError cleaning Google 
Chrome with BleachBit 4.0.0 (#890)

**Comment by az0** [comment] 2020-06-25 04:51
> error is gone
@gzu88bv 
Thank you for confirming. I will close the ticket

**Closed by az0** 2020-06-25 04:51 UTC
Labels: bug, bug: encoding, bug: regression
