### ISSUE TITLE
Wiping Free Space does not work in BB v.4.0.0

### ISSUE THREAD

**Issue by liar666** [bleachbit/bleachbit#1029] opened 2020-10-11 20:19 UTC
Hi,

I've just updated my PortableApps and got BleachBit Version 4.0.0 installed.

When I try to wipe the free space, I get error:
```
Wiping free disk space erases remnants of files that were deleted without shredding. It does not free up space.Error: _gui.free_disk_space: Function: Overwrite free disk space C:\
Traceback (most recent call last):
  File "C:\projects\bleachbit\bleachbit\Worker.py", line 87, in execute
  File "C:\projects\bleachbit\bleachbit\Command.py", line 145, in execute
  File "C:\projects\bleachbit\bleachbit\Cleaner.py", line 744, in wipe_path_func
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 917, in wipe_path
  File "C:\projects\bleachbit\bleachbit\FileUtilities.py", line 871, in temporaryfile
  File "C:\Python34\lib\tempfile.py", line 484, in NamedTemporaryFile
  File "C:\Python34\lib\tempfile.py", line 207, in _mkstemp_inner
OSError: [Errno 22] Invalid argument: 'C:\\tmp84zs17ma84WXeCrWYPI8ADH-nRV3Hyl.GmE6E52rtfuzmy4jlKUMNsYNJyP-7BYXMwi0OifULLInnFj3oBnp6fhoilSPd38L8m5O44WsUDsipu.VS89sHHNqtQmxlRXT764H4pO5Ca5KCT-knvSTkfjHkynIWwTubwwYSbByRv5R5o.KC2RqimXooXuscR4nZ5tl_y_lvEt09piISinjSmUvHGOe7rTXbClJV-NDkVsIkR4MbYfUjBf.0z3a1'

Disk space recovered: 0
Files deleted: 0
```

Tried to run the app as admin. I get the same error... There's apparently a bug in the temp file name generator.

**Comment by az0** [comment] 2020-10-24 17:01
This is a duplicate of https://github.com/bleachbit/bleachbit/issues/906 and was fixed. Try the latest version [4.1.0 beta](https://www.bleachbit.org/news/bleachbit-410-beta) or later

**Closed by az0** 2020-10-24 17:01 UTC
